import json
import re

A1_A2_MASSIVE_DATABASE = [
    # 1. Greetings & Social Expressions
    ("welcome", "Hush kelibsiz", "/ˈwel.kəm/", "Welcome to our English learning community!"),
    ("greetings", "Salomlashish, salomlar", "/ˈɡriː.tɪŋz/", "Send my warm greetings to your family."),
    ("apologize", "Kechirim so'ramoq", "/əˈpɒl.ə.dʒaɪz/", "I apologize for being late to the lesson."),
    ("pleasure", "Mamnuniyat, rohat", "/ˈpleʒ.ə/", "It is a pleasure to meet you today."),
    ("congratulate", "Tabriqlamoq", "/kənˈɡrætʃ.ə.leɪt/", "We congratulate you on passing your exam."),
    ("farewell", "Xayrlashuv", "/ˌfeəˈwel/", "They held a farewell party for their teacher."),
    ("excuse me", "Kechirasiz (murojaatda)", "/ɪkˈskjuːz miː/", "Excuse me, where is the nearest bank?"),
    ("good luck", "Omad yor bo'lsin", "/ɡʊd lʌk/", "Good luck on your IELTS test tomorrow!"),

    # 2. Family & Relationships
    ("relative", "Qarindosh, xesh-aqrobo", "/ˈrel.ə.tɪv/", "Many relatives gathered for the family reunion."),
    ("neighbor", "Qo'shni", "/ˈneɪ.bə/", "Our neighbor helped us carry the heavy boxes."),
    ("relationship", "Munosabat, aloqa", "/rɪˈleɪ.ʃən.ʃɪp/", "They maintain a strong, supportive friendship."),
    ("generation", "Avlod, nasl", "/ˌdʒen.əˈreɪ.ʃən/", "Three generations live together in that big house."),
    ("ancestor", "Ajdod, ota-bobo", "/ˈæn.ses.tə/", "Our ancestors built historic monuments in Bukhara."),
    ("sibling", "Aka-uka yoki opa-singil", "/ˈsɪb.lɪŋ/", "Do you have any brothers or sisters as siblings?"),
    ("parent", "Ota-ona", "/ˈpeə.rənt/", "Parents play a crucial role in raising children."),
    ("marriage", "Nikoh, oila qurish", "/ˈmær.ɪdʒ/", "They celebrated twenty years of happy marriage."),

    # 3. Time, Calendar & Seasons
    ("midnight", "Yarim tun", "/ˈmɪd.naɪt/", "The fireworks start exactly at midnight."),
    ("noon", "Peshin vaqti (soat 12:00)", "/nuːn/", "We usually have lunch at noon."),
    ("schedule", "Kun tartibi, dars jadvali", "/ˈʃed.juːl/", "Check your study schedule every morning."),
    ("century", "Asr, yuz yillik", "/ˈsen.tʃər.i/", "The monument was built in the fifteenth century."),
    ("decade", "O'n yillik", "/ˈdek.eɪd/", "Technology has advanced greatly over the past decade."),
    ("fortnight", "Ikki hafta (14 kun)", "/ˈfɔːt.naɪt/", "We are going on holiday for a fortnight."),
    ("annual", "Yillik, har yili bo'ladigan", "/ˈæn.ju.əl/", "The school holds an annual sports competition."),
    ("temporary", "Vaqtinchalik", "/ˈtem.pər.ər.i/", "This is just a temporary solution to the issue."),

    # 4. Numbers, Quantities & Measurements
    ("quarter", "Chorak, to'rtdan bir", "/ˈkwɔː.tə/", "The class starts at a quarter past nine."),
    ("double", "Ikki baravar, juft", "/ˈdʌb.əl/", "You can double your speed with regular practice."),
    ("amount", "Miqdor, summa", "/əˈmaʊnt/", "A large amount of water is saved by recycling."),
    ("average", "O'rtacha ko'rsatkich", "/ˈæv.ər.ɪdʒ/", "The average score in the test was seventy percent."),
    ("distance", "Masofa, olislik", "/ˈdɪs.təns/", "What is the distance between your home and school?"),
    ("height", "Balandlik, boy", "/haɪt/", "The building reaches a height of fifty meters."),
    ("weight", "Vazn, og'irlik", "/weɪt/", "Regular exercise helps maintain a healthy weight."),
    ("capacity", "Sig'im, hajm", "/kəˈpæs.ə.ti/", "The auditorium has a seating capacity of five hundred."),

    # 5. Food, Drink & Cooking
    ("delicious", "Lazzatli, shirin", "/dɪˈlɪʃ.əs/", "Plov is a delicious Uzbek traditional dish."),
    ("ingredient", "Tarkibiy masalliq", "/ɪnˈɡriː.di.ənt/", "Fresh vegetables are key ingredients for salad."),
    ("recipe", "Retsept, tayyorlash usuli", "/ˈres.ɪ.pi/", "Follow the baking recipe step by step."),
    ("nutrition", "Oziqlanish, taomlanish", "/njuːˈtrɪʃ.ən/", "Good nutrition gives you energy for studying."),
    ("beverage", "Ichimlik", "/ˈbev.ər.ɪdʒ/", "Hot tea is a popular beverage in cold weather."),
    ("breakfast", "Nonushta", "/ˈbrek.fəst/", "Eating a nutritious breakfast boots morning energy."),
    ("dessert", "Shirinlik, desert", "/dɪˈzɜːt/", "We ordered ice cream for dessert after dinner."),
    ("vegetarian", "Sabzavotli, vegetariancha", "/ˌvedʒ.ɪˈteə.ri.ən/", "She prefers a healthy vegetarian diet."),

    # 6. House, Furniture & Everyday Objects
    ("apartment", "Kvartira, xonadon", "/əˈpɑːt.mənt/", "They rented a bright apartment in the city center."),
    ("furniture", "Mebel, uy jihozlari", "/ˈfɜː.nɪ.tʃə/", "The living room is furnished with modern furniture."),
    ("appliance", "Maishiy texnika", "/əˈplaɪ.əns/", "A refrigerator is an essential kitchen appliance."),
    ("balcony", "Balkon, ayvon", "/ˈbæl.kə.ni/", "We enjoy drinking morning tea on the balcony."),
    ("basement", "Yerto'la, podval", "/ˈbeɪs.mənt/", "They store old tools and bicycles in the basement."),
    ("blanket", "Adyol, ko'rpa", "/ˈblæŋ.kɪt/", "Put a warm blanket over the bed on cold nights."),
    ("curtain", "Parda", "/ˈkɜː.tən/", "Open the window curtains to let in daylight."),
    ("mirror", "Ko'zgular, oyna", "/ˈmɪr.ə/", "There is a large mirror in the hallway."),

    # 7. City, Places & Transportation
    ("destination", "Manzil, boradigan joy", "/ˌdes.tɪˈneɪ.ʃən/", "Samarkand is a popular tourist destination."),
    ("passenger", "Yo'lovchi", "/ˈpæs.ən.dʒə/", "All passengers must fasten their seatbelts."),
    ("vehicle", "Transport vositasi", "/ˈvɪə.kəl/", "Bicycles and electric cars are eco-friendly vehicles."),
    ("pedestrian", "Piyoda", "/pəˈdes.tri.ən/", "Pedestrians should use the crosswalk to cross the street."),
    ("neighborhood", "Mahalla, atrof-tevarak", "/ˈneɪ.bə.hʊd/", "Our neighborhood is quiet, clean and friendly."),
    ("suburb", "Shahar atrofi", "/ˈsʌb.ɜːb/", "They moved to a peaceful suburb outside Tashkent."),
    ("traffic", "Yo'l harakati, tirbandlik", "/ˈtræf.ɪk/", "Heavy traffic delayed our bus during morning rush hour."),
    ("departure", "Jo'nash, uchib ketish", "/dɪˈpɑː.tʃə/", "Check the departure board for your flight time."),

    # 8. Nature, Animals & Weather
    ("environment", "Atrof-muhit, ekologiya", "/ɪnˈvaɪ.rən.mənt/", "Protecting the environment is our collective duty."),
    ("landscape", "Manzara, tabiat ko'rinishi", "/ˈlænd.skeɪp/", "The mountain landscape was covered in green trees."),
    ("atmosphere", "Atmosfera, muhit", "/ˈæt.məs.fɪə/", "The warm lighting created a cozy atmosphere."),
    ("forecast", "Ob-havo prognozi", "/ˈfɔː.kɑːst/", "According to the forecast, it will rain tomorrow."),
    ("creature", "Jonzot, tirik mavjudot", "/ˈkriː.tʃə/", "Dolphins are intelligent ocean creatures."),
    ("wildlife", "Yovvoyi tabiat", "/ˈwaɪld.laɪf/", "The national park protects local wildlife species."),
    ("disaster", "Tabiiy kutilmagan kulfat, falokat", "/dɪˈzɑː.stə/", "Earthquakes are unpredictable natural disasters."),
    ("climate", "Iqlim", "/ˈklaɪ.mət/", "Central Asia has a continental climate with warm summers."),

    # 9. Body & Health
    ("symptom", "Alomat, belgi", "/ˈsɪmp.təm/", "A high fever is a common symptom of flu."),
    ("treatment", "Davolash, muolaja", "/ˈtriːt.mənt/", "The doctor prescribed effective medical treatment."),
    ("prevention", "Oldini olish, profilaktika", "/prɪˈven.ʃən/", "Hand washing is key to disease prevention."),
    ("recovery", "Sog'ayish, tiklanish", "/rɪˈskʌv.ər.i/", "We wish you a full and speedy recovery."),
    ("exercise", "Jismoniy mashq", "/ˈek.sə.saɪz/", "Daily physical exercise boosts your immunity."),
    ("pharmacy", "Dorixona", "/ˈfɑː.mə.si/", "You can buy medicine at the local pharmacy."),
    ("patient", "Bemor, sabrli", "/ˈpeɪ.ʃənt/", "The doctor examined the patient carefully."),
    ("diet", "Parhez, ovqatlanish rejasi", "/ˈdaɪ.ət/", "A balanced diet provides essential vitamins."),

    # 10. Clothes & Fashion
    ("outfit", "Kiyim-kechak jamlanmasi", "/ˈaʊt.fɪt/", "She chose a stylish outfit for the ceremony."),
    ("garment", "Kiyim, ust-bosh", "/ˈɡɑː.mənt/", "Cotton is used to manufacture soft garments."),
    ("footwear", "Poyabzal", "/ˈfʊt.weə/", "Wear comfortable footwear for long walks."),
    ("accessory", "Akkessuar, bezak", "/əkˈses.ər.i/", "A leather belt is a practical fashion accessory."),
    ("uniform", "Forma, maxsus kiyim", "/ˈjuː.nɪ.fɔːm/", "Students wear blue school uniforms every day."),
    ("wardrobe", "Kiyim javoni, garderob", "/ˈwɔː.drəʊb/", "He organized his winter coats in the wardrobe."),
    ("material", "Mato, material", "/məˈtɪə.ri.əl/", "Silk is a soft and luxurious textile material."),
    ("fashionable", "Zamonaga mos, urfdagi", "/ˈfæʃ.ən.ə.bəl/", "She wears fashionable glasses to school."),

    # 11. Work, Jobs & Education
    ("profession", "Kasb, mutaxassislik", "/prəˈfeʃ.ən/", "Teaching is a noble and rewarding profession."),
    ("qualification", "Malaka, diplom", "/ˌkwɒl.ɪ.fɪˈkeɪ.ʃən/", "She gained a professional writing qualification."),
    ("employment", "Ish bilan ta'minlanganlik", "/ɪmˈplɔɪ.mənt/", "The government aims to boost youth employment."),
    ("colleague", "Hamkasb", "/ˈkɒl.iːɡ/", "I collaborate closely with my office colleagues."),
    ("salary", "Oylik maosh", "/ˈsæl.ər.i/", "He receives a competitive monthly salary."),
    ("curriculum", "O'quv dasturi", "/kəˈrɪk.jə.ləm/", "The school curriculum includes computer coding."),
    ("assignment", "Vazifa, topshiriq", "/əˈsaɪn.mənt/", "Submit your writing assignment by Friday."),
    ("certificate", "Sertifikat, guvohnoma", "/səˈtɪf.ɪ.kət/", "You will receive an official completion certificate."),

    # 12. Hobbies, Free Time & Sports
    ("tournament", "Musobaqa, turnir", "/ˈtʊə.nə.mənt/", "Our football team won the regional tournament."),
    ("entertainment", "Ko'ngilochar mashg'ulot", "/ˌen.təˈteɪn.mənt/", "The festival offers music and dance entertainment."),
    ("leisure", "Bo'sh vaqt, hordiq", "/ˈleʒ.ə/", "He enjoys reading novels in his leisure time."),
    ("champion", "Chempion, g'olib", "/ˈtʃæm.pi.ən/", "She became the national chess champion at age sixteen."),
    ("spectator", "Tomoshabin", "/spekˈteɪ.tə/", "Thousands of spectators filled the stadium."),
    ("exhibition", "Ko'rgazma", "/ˌek.sɪˈbɪʃ.ən/", "We visited an art exhibition of modern paintings."),
    ("orchestra", "Orkestr", "/ˈɔː.kɪ.strə/", "The orchestra played beautiful classical music."),
    ("recreation", "Hordiq chiqarish, dam olish", "/ˌrek.riˈeɪ.ʃən/", "Parks provide spaces for public outdoor recreation."),

    # 13. Emotions & Feelings
    ("delighted", "Juda xursand, mamnun", "/dɪˈlaɪ.tɪd/", "She was delighted to hear the good news."),
    ("embarrassed", "Hijolatda qolgan, uyalgan", "/ɪmˈbær.əst/", "He felt embarrassed when he forgot his lines."),
    ("exhausted", "Haddan tashqari charchagan", "/ɪɡˈzɔː.stɪd/", "After the long marathon, the runners were exhausted."),
    ("frightened", "Qo'rqqan, cho'chigan", "/ˈfraɪ.tənd/", "The loud thunder frightened the small puppy."),
    ("jealous", "Rashkchi, hasadg'oy", "/ˈdʒel.əs/", "Avoid being jealous of other people's achievements."),
    ("satisfied", "Qoniqqan, mamnun", "/ˈsæt.ɪs.faɪd/", "We are satisfied with the survey results."),
    ("surprised", "Hayron qolgan", "/səˈpraɪzd/", "She was surprised by the unexpected birthday gift."),
    ("sympathetic", "Hamdard, xayrixoh", "/ˌsɪm.pəˈθet.ɪk/", "The teacher was sympathetic when I felt unwell."),

    # 14. Prepositions & Connectors
    ("furthermore", "Bundan tashqari, qolaversa", "/ˌfɜː.ðəˈmɔː/", "The course is free; furthermore, books are provided."),
    ("however", "Biroq, lekin", "/haʊˈev.ə/", "The test was hard; however, everyone passed."),
    ("therefore", "Shu sababli, demak", "/ˈðeə.fɔː/", "She practiced daily; therefore, her score improved."),
    ("meanwhile", "Shu asnoda, bu orada", "/ˈmiːn.waɪl/", "Boil the water; meanwhile, chop the vegetables."),
    ("despite", "Qaramasdan, qaramay", "/dɪˈspaɪt/", "They enjoyed the walk despite the rainy weather."),
    ("although", "Garchi, bo'lsada", "/ɔːlˈðəʊ/", "Although it was cold, we went for a swim."),
    ("in addition", "Qo'shimcha ravishda", "/ɪn əˈdɪʃ.ən/", "In addition to English, she speaks French fluently."),
    ("otherwise", "Aks holda, bo'lmasa", "/ˈʌð.ə.waɪz/", "Hurry up; otherwise, we will miss the train."),

    # 15. Core Verbs
    ("accept", "Qabul qilmoq, rozi bo'lmoq", "/əkˈsept/", "She accepted the scholarship offer with joy."),
    ("achieve", "Erishmoq, qo'lga kiritmoq", "/əˈtʃiːv/", "Hard work helps you achieve your dreams."),
    ("admire", "Havas qilmoq, qoyil qolmoq", "/ədˈmaɪə/", "I admire her dedication to learning new skills."),
    ("admit", "Tan olmoq", "/ədˈmɪt/", "He admitted making a mistake on the calculation."),
    ("advise", "Maslahat bermoq", "/ədˈvaɪz/", "Tutors advise students to review daily flashcards."),
    ("afford", "Qurbi yetmoq, sotib ola bilmoq", "/əˈfɔːd/", "We can afford to buy a new study desk now."),
    ("agree", "Rozi bo'lmoq, qo'shilmoq", "/əˈɡriː/", "I agree with your suggestion about essay structure."),
    ("allow", "Ruxsat bermoq", "/əˈlaʊ/", "Libraries allow quiet study areas for students."),
    ("announce", "E'lon qilmoq", "/əˈnaʊns/", "The host announced the winner of the competition."),
    ("appear", "Ko'rinmoq, paydo bo'lmoq", "/əˈpɪə/", "New features appear on the app after updating."),
    ("apply", "Hujjat topshirmoq, qo'llamoq", "/əˈplaɪ/", "Apply online before the official deadline."),
    ("appreciate", "Qadrlamoq, minnatdor bo'lmoq", "/əˈpriː.ʃi.eɪt/", "I appreciate your help with my project."),
    ("approve", "Ma'qullamoq, tasdiqlamoq", "/əˈpruːv/", "The board approved the new building design."),
    ("arrange", "Tashkillashtirmoq, tartibga solmoq", "/əˈreɪndʒ/", "Let's arrange our notes in chronological order."),
    ("arrive", "Yetib kelmoq", "/əˈraɪv/", "The express train will arrive in ten minutes."),
    ("assist", "Yordam bermoq, ko'maklashmoq", "/əˈsɪst/", "Lab assistants help students during experiments."),
    ("assume", "Taxmin qilmoq, deb o'ylamoq", "/əˈsjuːm/", "Do not assume the test will be easy without prep."),
    ("attach", "Biriktirmoq, ilova qilmoq", "/əˈtætʃ/", "Please attach your resume to the email."),
    ("attempt", "Harakat qilib ko'rmoq, urinmoq", "/əˈtempt/", "She attempted to solve the puzzle in five minutes."),
    ("attend", "Qatnashmoq, borib turmoq", "/əˈtend/", "Students must attend all laboratory sessions."),
    ("attract", "Jalb etmoq, o'ziga tortmoq", "/əˈtrækt/", "Bright colors attract the attention of children."),
    ("avoid", "Qochmoq, chetlab o'tmoq", "/əˈvɔɪd/", "Avoid spending too much time on social media."),
    ("become", "Bo'lmoq, aylanmoq", "/bɪˈkʌm/", "Practice helps you become a fluent speaker."),
    ("beg", "Yalinmoq, so'ramoq", "/beɡ/", "The child begged for one more story before bed."),
    ("begin", "Boshlamoq", "/bɪˈɡɪn/", "Lessons begin promptly at eight thirty in the morning."),
    ("behave", "O'zini tutmoq, odob saqlamoq", "/bɪˈheɪv/", "Children are taught to behave politely at school."),
    ("believe", "Ishonmoq", "/bɪˈliːv/", "Believe in your ability to master any subject."),
    ("belong", "Tegishli bo'lmoq", "/bɪˈlɒŋ/", "These books belong to the university library."),
    ("borrow", "Qarzga olmoq", "/ˈbɒr.əʊ/", "Can I borrow your ruler for a moment?"),
    ("breathe", "Nafas olmoq", "/briːð/", "Take a deep breath to calm your exam nerves."),
    ("build", "Qurmoq, bino etmoq", "/bɪld/", "Engineers build durable bridges across rivers."),
    ("calculate", "Hisoblamoq", "/ˈkæl.kjə.leɪt/", "Use a calculator to calculate the total budget."),
    ("cancel", "Bekor qilmoq", "/ˈkæn.səl/", "They cancelled the outdoor match due to rain."),
    ("capture", "Ushlamoq, tasvirga olmoq", "/ˈkæp.tʃə/", "The photographer captured the sunset beautifully."),
    ("cause", "Sabab bo'lmoq", "/kɔːz/", "Careless driving can cause traffic accidents."),
    ("celebrate", "Nishonlamoq", "/ˈsel.ə.breɪt/", "We gather to celebrate family birthdays together."),
    ("challenge", "Chaqiriq tashlamoq, sinamoq", "/ˈtʃæl.ɪndʒ/", "New projects challenge our problem-solving skills."),
    ("change", "O'zgartirmoq, o'zgarmoq", "/tʃeɪndʒ/", "Technology changes the way we study and work."),
    ("choose", "Tanlamoq", "/tʃuːz/", "Choose the correct option from the drop-down menu."),
    ("claim", "Da'vo qilmoq, ta'kidlamoq", "/kleɪm/", "The author claims that reading boosts memory."),
    ("collect", "Yig'moq, to'plamoq", "/kəˈlekt/", "Students collect research data for their thesis."),
    ("combine", "Birlashtirmoq, qo'shmoq", "/kəmˈbaɪn/", "Combine exercise with good nutrition for health."),
    ("command", "Buyurmoq, boshqarmoq", "/kəˈmɑːnd/", "The general commanded the troops to halt."),
    ("communicate", "Muloqot qilmoq", "/kəˈmjuː.nɪ.keɪt/", "English helps people communicate across borders."),
    ("compare", "Taqqoslamoq", "/kəmˈpeə/", "Compare the advantages of both study methods."),
    ("compete", "Musobaqalashmoq, bellashmoq", "/kəmˈpiːt/", "Athletes compete for gold medals in the games."),
    ("complain", "Shikoyat qilmoq", "/kəmˈpleɪn/", "Customers complain if service is delayed."),
    ("complete", "Tugatmoq, to'ldirmoq", "/kəmˈpliːt/", "Complete the form with your personal details."),
    ("concentrate", "Diqqatni jamlamoq", "/ˈkɒn.sən.treɪt/", "Quiet environments help you concentrate on reading."),
    ("conclude", "Xulosa qilmoq", "/kənˈkluːd/", "The essay concludes with a summary of key points."),
    ("confirm", "Tasdiqlamoq", "/kənˈfɜːm/", "Confirm your email address by clicking the link."),
    ("connect", "Bog'lamoq, ulamoq", "/kəˈnekt/", "Connect to the Wi-Fi network to access notes."),
    ("consider", "O'ylab ko'rmoq, hisoblamoq", "/kənˈsɪd.ə/", "Consider all options before taking a final decision."),
    ("consist", "Tashkil topmoq, iborat bo'lmoq", "/kənˈsɪst/", "The exam consists of three main modules."),
    ("construct", "Qurmoq, bino qilmoq", "/kənˈstrʌkt/", "Workers construct high-rise modern apartments."),
    ("contain", "O'z ichiga olmoq, saqlamoq", "/kənˈteɪn/", "Fresh fruits contain essential vitamins."),
    ("continue", "Davom ettirmoq", "/kənˈtɪn.juː/", "Continue practicing until you feel comfortable."),
    ("contribute", "Hissa qo'shmoq", "/kənˈtrɪb.juːt/", "Every member contributes to group success."),
    ("control", "Boshqarmoq, nazorat qilmoq", "/kənˈtrəʊl/", "Learn to control your time during tests."),
    ("convert", "O'girmoq, aylantirmoq", "/kənˈvɜːt/", "Convert currencies using online banking apps."),
    ("convince", "Ishontirmoq", "/kənˈvɪns/", "She convinced her parents to let her travel."),
    ("create", "Yaratmoq", "/kriˈeɪt/", "Artists create inspiring paintings."),
    ("damage", "Zarar yetkazmoq", "/ˈdæm.ɪdʒ/", "Storms can damage electric power lines."),
    ("decide", "Qaror qilmoq", "/dɪˈsaɪd/", "Decide on your daily goals every morning."),
    ("declare", "E'lon qilmoq, bildirmoq", "/dɪˈkleər/", "Customs officers ask if you have goods to declare."),
    ("decorate", "Bezatmoq, pardozlamoq", "/ˈdek.ə.reɪt/", "They decorate the house for New Year celebrations."),
    ("decrease", "Kamaytirmoq", "/dɪˈkriːs/", "Noise levels decrease late in the evening."),
    ("define", "Ta'riflamoq, belgilamoq", "/dɪˈfaɪn/", "Dictionaries define the precise meaning of words."),
    ("delay", "Kechiktirmoq", "/dɪˈleɪ/", "Bad weather delayed the takeoff of our flight."),
    ("deliver", "Yetkazib bermoq", "/dɪˈlɪv.ə/", "Couriers deliver packages directly to your door."),
    ("demand", "Talab qilmoq", "/dɪˈmɑːnd/", "Modern jobs demand digital and language skills."),
    ("demonstrate", "Ko'rsatib bermoq, namoyish etmoq", "/ˈdem.ən.streɪt/", "The teacher demonstrated the chemistry experiment."),
    ("depend", "Bog'liq bo'lmoq", "/dɪˈpend/", "Exam scores depend on effort and revision."),
    ("describe", "Tasvirlamoq", "/dɪˈskraɪb/", "Describe your favorite childhood memory."),
    ("design", "Loyihalashtirmoq, yaratmoq", "/dɪˈzaɪn/", "Engineers design safe and modern buildings."),
    ("destroy", "Yo'q qilmoq, vayron etmoq", "/dɪˈstrɔɪ/", "Fires destroy large areas of forest land."),
    ("detail", "Batafsil tushuntirmoq", "/ˈdiː.teɪl/", "The manual details step-by-step instructions."),
    ("develop", "Rivojlantirmoq", "/dɪˈvel.əp/", "Students develop critical thinking in debate club."),
    ("disappear", "Yo'qolmoq, g'oyib bo'lmoq", "/ˌdɪs.əˈpɪə/", "The fog disappeared as the sun rose higher."),
    ("discover", "Kashf etmoq", "/dɪˈskʌv.ə/", "Researchers discover new medical treatments."),
    ("discuss", "Muhokama qilmoq", "/dɪˈskʌs/", "Discuss essay topics in small study groups."),
    ("display", "Namoyish qilmoq, ko'rsatmoq", "/dɪˈspleɪ/", "Screens display real-time arrival information."),
    ("distribute", "Tarqatmoq", "/dɪˈstrɪb.juːt/", "Volunteers distribute warm food to families."),
    ("divide", "Bo'lmoq, ajratmoq", "/dɪˈvaɪd/", "Divide your study time into short focused intervals."),
    ("doubt", "Shubhalanmoq", "/daʊt/", "Never doubt your capacity to learn and grow."),
    ("earn", "Ishlab topmoq, qozonmoq", "/ɜːn/", "Hard work allows you to earn respect and income."),
    ("educate", "Ta'lim bermoq, tarbiyalamoq", "/ˈedʒ.u.keɪt/", "Schools educate young minds for future roles."),
    ("embarrass", "Hijolat qilmoq, uyaltirmoq", "/ɪmˈbær.əs/", "Do not let minor mistakes embarrass you in public."),
    ("emerge", "Namoyon bo'lmoq, chiqmoq", "/ɪˈmɜːdʒ/", "New technologies emerge every single year."),
    ("encourage", "Ruhlantirmoq", "/ɪnˈkʌr.ɪdʒ/", "Parents encourage their children to read books."),
    ("enjoy", "Huzurlanmoq, zavqlanmoq", "/ɪnˈdʒɔɪ/", "I enjoy listening to podcasts while commuting."),
    ("entertain", "Xushnud etmoq, ko'ngil olmoq", "/ˌen.təˈteɪn/", "Comedians entertain the audience with funny acts."),
    ("escape", "Qochib qutulmoq", "/ɪˈskeɪp/", "Birds escape cold climates by flying south."),
    ("establish", "Tashkil etmoq, asos solmoq", "/ɪˈstæb.lɪʃ/", "The university was established in 1920."),
    ("evaluate", "Baho bermoq", "/ɪˈvæl.ju.eɪt/", "Examiners evaluate fluency and coherence."),
    ("examine", "Tekshirmoq, imtihon qilmoq", "/ɪɡˈzæm.ɪn/", "Doctors examine patients to diagnose illnesses."),
    ("exchange", "Almashtirmoq, fikr almashmoq", "/ɪksˈtʃeɪndʒ/", "Students exchange study tips before exams."),
    ("exist", "Mavjud bo'lmoq, yashamoq", "/ɪɡˈzɪst/", "Water is necessary for life to exist on Earth."),
    ("expand", "Kengaytirmoq, kattalashtirmoq", "/ɪkˈspænd/", "Reading helps expand your active vocabulary."),
    ("expect", "Kutmoq, umid qilmoq", "/ɪkˈspekt/", "We expect good news from the exam committee."),
    ("explain", "Tushuntirmoq", "/ɪkˈspleɪn/", "Tutors explain rules with clear visual examples."),
    ("explore", "Tadqiq qilmoq, o'rganib chiqmoq", "/ɪkˈsplɔː/", "Travelers love to explore historic old cities."),
    ("express", "Iroda etmoq, bildirmoq", "/ɪkˈspres/", "Art lets people express their innermost thoughts."),
    ("extend", "Uzaytirmoq, cho'zmoq", "/ɪkˈstend/", "The school decided to extend the project deadline."),
    ("fail", "Muvaffaqiyatsizlikka uchramoq", "/feɪl/", "Failure is just a stepping stone to success."),
    ("fear", "Qo'rqmoq", "/fɪə/", "Do not fear making mistakes when practicing speaking."),
    ("figure out", "Tushunib yetmoq, yechim topmoq", "/ˈfɪɡ.ər aʊt/", "I need to figure out how to solve this equation."),
    ("fill", "To'ldirmoq", "/fɪl/", "Fill the water bottle before starting your workout."),
    ("finish", "Tugatmoq", "/ˈfɪn.ɪʃ/", "Finish your assignment before going out to play."),
    ("focus", "Diqqatni qaratmoq", "/ˈfəʊ.kəs/", "Focus on your goals and avoid distractions."),
    ("follow", "Egasida yurmoq, rioya qilmoq", "/ˈfɒl.əʊ/", "Follow the instructions carefully during the test."),
    ("forgive", "Kechirmoq", "/fəˈɡɪv/", "Forgiving mistakes creates peace in relationships."),
    ("gather", "To'plamoq, yig'ilmoq", "/ˈɡæð.ə/", "Students gather in the hall for the assembly."),
    ("generate", "Yaratmoq, hosil qilmoq", "/ˈdʒen.ə.reɪt/", "Solar panels generate clean electrical energy."),
    ("govern", "Boshqarmoq, idora etmoq", "/ˈɡʌv.ən/", "The council governs local municipal services."),
    ("graduate", "Bitirmoq (o'quv yurti)", "/ˈɡrædʒ.u.eɪt/", "She will graduate from university next summer."),
    ("guarantee", "Kafolatlamoq", "/ˌɡær.ənˈtiː/", "Practice does not guarantee perfection, but builds progress."),
    ("handle", "Uddalamoq, ko'tarmoq", "/ˈhæn.dəl/", "She knows how to handle stress during exam week."),
    ("happen", "Yuz bermoq, sodir bo'lmoq", "/ˈhæp.ən/", "Accidents happen when drivers lose focus."),
    ("help", "Yordam bermoq", "/help/", "Friends help each other during difficult times."),
    ("hesitate", "Ikkilanmoq, shubhalanmoq", "/ˈhez.ɪ.teɪt/", "Do not hesitate to ask questions in class."),
    ("identify", "Aniqlamoq, tanimoq", "/aɪˈden.tɪ.faɪ/", "Identify key keywords in the reading passage."),
    ("ignore", "E'tiborsiz qoldirmoq", "/ɪɡˈnɔː/", "Ignore minor distractions while working."),
    ("illustrate", "Tasvirlamoq, ko'rgazmali tushuntirmoq", "/ˈɪl.ə.streɪt/", "Diagrams illustrate how the heart pumps blood."),
    ("imagine", "Tasavvur qilmoq", "/ɪˈmædʒ.ɪn/", "Imagine living in a historic European city."),
    ("impact", "Ta'sir ko'rsatmoq", "/ˈɪm.pækt/", "Daily study habits directly impact your final score."),
    ("implement", "Joriy etmoq, amalga oshirmoq", "/ˈɪm.plɪ.ment/", "Schools implement new interactive teaching software."),
    ("imply", "Nazarda tutmoq, shama qilmoq", "/ɪmˈplaɪ/", "Her tone implied that she was dissatisfied."),
    ("improve", "Rivojlantirmoq", "/ɪmˈpruːv/", "Reading books will improve your vocabulary."),
    ("include", "O'z ichiga olmoq", "/ɪnˈkluːd/", "The fee includes breakfast and hotel stay."),
    ("increase", "Oshirmoq", "/ɪnˈkriːs/", "The store plans to increase sales next quarter."),
    ("indicate", "Ko'rsatmoq, bildirmoq", "/ˈɪn.dɪ.keɪt/", "Red signs indicate danger or emergency exits."),
    ("inform", "Xabar qilmoq", "/ɪnˈfɔːm/", "Inform the manager if you need extra resources."),
    ("inherit", "Meros qilib olmoq", "/ɪnˈher.ɪt/", "She inherited her grandmother's vintage watch."),
    ("initiate", "Boshlamoq, yo'lga qo'ymoq", "/ɪˈnɪʃ.i.eɪt/", "The city initiated a recycling drive this spring."),
    ("injure", "Jarohatlamoq", "/ˈɪn.dʒə/", "Wear helmets to prevent injuring your head."),
    ("insist", "Taqaza qilmoq, oyog'ini tirab olmoq", "/ɪnˈsɪst/", "He insisted on paying for the coffee."),
    ("inspect", "Tekshirib chiqmoq", "/ɪnˈspekt/", "Engineers inspect safety equipment every month."),
    ("inspire", "Ilhomlantirmoq", "/ɪnˈspaɪə/", "Great teachers inspire students to achieve greatness."),
    ("install", "O'rnatmoq, joylashtirmoq", "/ɪnˈstɔːl/", "Install the latest version of the app for new features."),
    ("instruct", "Ko'rsatma bermoq, o'rgatmoq", "/ɪnˈstrʌkt/", "Flight attendants instruct passengers on safety."),
    ("insult", "Haqorat qilmoq", "/ɪnˈsʌlt/", "Never insult others during debates."),
    ("intend", "Niyat qilmoq", "/ɪnˈtend/", "I intend to complete the course by December."),
    ("interact", "O'zaro muloqot qilmoq", "/ˌɪn.təˈrækt/", "Students interact naturally in group activities."),
    ("interrupt", "Xalaqit bermoq, gapini bo'lmoq", "/ˌɪn.təˈrʌpt/", "Do not interrupt the speaker while they are talking."),
    ("introduce", "Tanishtirmoq", "/ˌɪn.trəˈdjuːs/", "Let me introduce my new classmate to you."),
    ("invent", "Kashf etmoq, o'ylab topmoq", "/ɪnˈvent/", "Edison invented the practical incandescent light bulb."),
    ("invest", "Sarmoya kiritmoq", "/ɪnˈvest/", "Investing in education yields lifelong benefits."),
    ("investigate", "Tadqiq etmoq, surushtirmoq", "/ɪnˈves.tɪ.ɡeɪt/", "Detectives investigate unsolved mystery cases."),
    ("invite", "Taklif qilmoq", "/ɪnˈvaɪt/", "We invited our friends over for dinner."),
    ("involve", "Jalb etmoq, qamrab olmoq", "/ɪnˈvɒlv/", "The project involves creative teamwork."),
    ("issue", "Tarqatmoq, berib yubormoq", "/ˈɪʃ.uː/", "The library issues digital reader cards."),
    ("join", "Qo'shilmoq, a'zo bo'lmoq", "/dʒɔɪn/", "Join our English speaking club on Telegram."),
    ("judge", "Baho bermoq, hukm qilmoq", "/dʒʌdʒ/", "Never judge a book by its cover."),
    ("justify", "Oqlamoq, asoslab bermoq", "/ˈdʒʌs.tɪ.faɪ/", "Justify your answer with evidence from the text."),
    ("keep", "Saqlamoq, ushlab turmoq", "/kiːp/", "Keep your room clean and organized."),
    ("lack", "Yetishmaslik, tanqis bo'lmoq", "/læk/", "Lack of sleep affects concentration levels."),
    ("lead", "Boshlamoq, yetakchilik qilmoq", "/liːd/", "Hard work leads to success."),
    ("learn", "O'rganmoq", "/lɜːn/", "Learn ten new words every day."),
    ("lend", "Qarzga berib turmoq", "/lend/", "Can you lend me your pencil for the exam?"),
    ("limit", "Cheklamoq", "/ˈlɪm.ɪt/", "Limit your screen time before sleep."),
    ("listen", "Tinglamoq, quloq solmoq", "/ˈlɪs.ən/", "Listen to native audio podcasts daily."),
    ("locate", "Joylashtirmoq, topmoq", "/ləʊˈkeɪt/", "Use the map to locate the university hall."),
    ("maintain", "Saqlamoq, ta'minlamoq", "/meɪnˈteɪn/", "Maintain a steady study schedule."),
    ("manage", "Boshqarmoq, uddalamoq", "/ˈmæn.ɪdʒ/", "Manage your study time efficiently."),
    ("manufacture", "Ishlab chiqarmoq", "/ˌmæn.jəˈfæk.tʃə/", "Factories manufacture electronic components."),
    ("measure", "O'lchamoq", "/ˈmeʒ.ə/", "Rulers measure length in centimeters."),
    ("mention", "Eslatib o'tmoq, gapirmoq", "/ˈmen.ʃən/", "Did he mention the exact exam time?"),
    ("mind", "E'tibor bermoq, qarshi bo'lmoq", "/maɪnd/", "Do you mind opening the window?"),
    ("motivate", "Ruhlantirmoq, həvəslendirmek", "/ˈməʊ.tɪ.veɪt/", "Good goals motivate you to work harder."),
    ("navigate", "Yo'l topmoq, harakatlanmoq", "/ˈnæv.ɪ.ɡeɪt/", "GPS apps help drivers navigate city streets."),
    ("negotiate", "Muzokara olib bormoq", "/nəˈɡəʊ.ʃi.eɪt/", "Diplomats negotiate peace treaties."),
    ("notice", "Payqamoq", "/ˈnəʊ.tɪs/", "Did you notice the new noticeboard sign?"),
    ("obey", "Itoat etmoq, boysunmoq", "/əˈbeɪ/", "Drivers must obey traffic regulations."),
    ("obtain", "Qo'lga kiritmoq", "/əbˈteɪn/", "Obtain a passport before traveling overseas."),
    ("occur", "Sodir bo'lmoq", "/əˈkɜː/", "Solar eclipses occur rarely."),
    ("offer", "Taklif qilmoq", "/ˈɒf.ə/", "The company offered him a modern job."),
    ("operate", "Boshqarmoq, ishlamoq", "/ˈɒp.ər.eɪt/", "Technicians operate heavy machinery safely."),
    ("opportunity", "Imkoniyat", "/ˌɒp.əˈtʃuː.nə.ti/", "Education creates life opportunities."),
    ("organize", "Tashkillashtirmoq", "/ˈɔː.ɡən.aɪz/", "Organize your notes into color-coded folders."),
    ("overcome", "Yengib o'tmoq, oshmoq", "/ˌəʊ.vəˈkʌm/", "Practice helps overcome speaking fear."),
    ("participate", "Qatnashmoq", "/pɑːˈtɪs.ɪ.peɪt/", "Participate in group discussions actively."),
    ("perform", "Bajarmoq, ijro etmoq", "/pəˈfɔːm/", "Musicians perform live on stage."),
    ("persuade", "Kondirmoq, ko'ndirmoq", "/pəˈsweɪd/", "She persuaded her friend to join the gym."),
    ("plan", "Rejalashtirmoq", "/plæn/", "Plan your daily study session in advance."),
    ("predict", "Oldindan aytmoq, bashorat qilmoq", "/prɪˈdɪkt/", "Meteorologists predict weekend weather."),
    ("prefer", "Afzal ko'rmoq", "/prɪˈfɜː/", "I prefer tea over coffee in the morning."),
    ("prepare", "Tayyorlanmoq", "/prɪˈpeə/", "Prepare your materials before class begins."),
    ("present", "Taqdim etmoq", "/prɪˈzent/", "Students present their slides to the class."),
    ("prevent", "Oldini olmoq", "/prɪˈvent/", "Seatbelts prevent injuries in accidents."),
    ("produce", "Ishlab chiqarmoq", "/prəˈdjuːs/", "Solar panels produce clean energy."),
    ("protect", "Himoyalamoq", "/prəˈtekt/", "Protect your skin from sun damage."),
    ("provide", "Ta'minlamoq", "/prəˈvaɪd/", "Libraries provide free digital books."),
    ("publish", "Chop etmoq, nashr qilmoq", "/ˈpʌb.lɪʃ/", "The journal published new research findings."),
    ("punish", "Jazolamoq", "/ˈpʌn.ɪʃ/", "Break the rules and you may face penalties."),
    ("pursue", "Quvmoq, intilmoq", "/pəˈsjuː/", "Pursue your academic goals with passion."),
    ("react", "Munosabat bildirmoq", "/riˈækt/", "Stay calm and react sensibly to problems."),
    ("receive", "Qabul qilmoq, olmoq", "/rɪˈsiːv/", "You will receive an email confirmation."),
    ("recommend", "Tavsiya etmoq", "/ˌrek.əˈmend/", "Teachers recommend daily revision."),
    ("reduce", "Qisqartirmoq", "/rɪˈdjuːs/", "Recycling helps reduce waste."),
    ("refer", "Havola qilmoq, qaramoq", "/rɪˈfɜː/", "Refer to the textbook dictionary for meanings."),
    ("reflect", "Aks ettirmoq, fikr yuritmoq", "/rɪˈflekt/", "Mirrors reflect daylight into the corridor."),
    ("refuse", "Rad etmoq", "/rɪˈfjuːz/", "He refused to give up on his dreams."),
    ("regret", "Afsuslanmoq", "/rɪˈɡret/", "Do not regret mistakes; learn from them."),
    ("relax", "Hordiq chiqarmoq, tinchlanmoq", "/rɪˈlæks/", "Listen to soft music to relax after work."),
    ("release", "Chiqarmoq, qo'yib yubormoq", "/rɪˈliːs/", "The band released a new music album."),
    ("rely", "Suyanmoq, ishonmoq", "/rɪˈlaɪ/", "You can rely on reliable friends."),
    ("remember", "Eslamoq", "/rɪˈmem.bə/", "Remember to save your progress."),
    ("remind", "Eslatmoq", "/rɪˈmaɪnd/", "Remind me to call the tutor tomorrow."),
    ("remove", "Olib tashlamoq", "/rɪˈmuːv/", "Remove dust from the computer screen."),
    ("repair", "Tuzatmoq", "/rɪˈpeə/", "Technicians repair faulty machinery."),
    ("repeat", "Takrorlamoq", "/rɪˈpiːt/", "Repeat new words aloud to improve accent."),
    ("replace", "Almashtirmoq", "/rɪˈpleɪs/", "Replace old bulbs with energy-saving LEDs."),
    ("reply", "Javob qaytarmoq", "/rɪˈplaɪ/", "Reply to the invitation email promptly."),
    ("report", "Hisobot bermoq, ma'lum qilmoq", "/rɪˈpɔːt/", "Reporters report news from around the world."),
    ("represent", "Vakillik qilmoq, namoyon etmoq", "/ˌrep.rɪˈzent/", "Diplomats represent their countries abroad."),
    ("request", "Iltimos qilmoq", "/rɪˈkwest/", "Submit a written request for additional time."),
    ("require", "Talab etmoq", "/rɪˈkwaɪə/", "Learning requires dedication."),
    ("research", "Tadqiqot o'tkazmoq", "/rɪˈsɜːtʃ/", "Scientists research renewable fuel sources."),
    ("resist", "Qarshilik ko'rsatmoq", "/rɪˈzɪst/", "Resist the urge to check social media during study."),
    ("resolve", "Hal qilmoq, yechim topmoq", "/rɪˈzɒlv/", "Mediation helps resolve neighbor conflicts."),
    ("respect", "Hurmat qilmoq", "/rɪˈspekt/", "Respect teachers and fellow students."),
    ("respond", "Javob bermoq", "/rɪˈspɒnd/", "Respond clearly to examiner questions."),
    ("restrict", "Cheklamoq", "/rɪˈstrɪkt/", "Park rules restrict parking near gates."),
    ("result", "Natijaga erishmoq", "/rɪˈzʌlt/", "Hard work results in higher scores."),
    ("retain", "Saqlab qolmoq", "/rɪˈteɪn/", "Flashcards help retain vocabulary long term."),
    ("review", "Qayta ko'rib chiqmoq, takrorlamoq", "/rɪˈvjuː/", "Review your flashcards every evening."),
    ("revise", "Takrorlamoq (imtihon oldi)", "/rɪˈvaɪz/", "Revise key grammar points before the test."),
    ("reward", "Mukofotlamoq", "/rɪˈwɔːd/", "Hard work rewards you with great success."),
    ("satisfy", "Qoniqtirmoq", "/ˈsæt.ɪs.faɪ/", "Good service satisfies customers."),
    ("save", "Saqlamoq, tejamoq", "/seɪv/", "Save money for future university fees."),
    ("search", "Qidirmoq", "/sɜːtʃ/", "Search online for sample essay topics."),
    ("select", "Tanlamoq", "/sɪˈlekt/", "Select the best answer from options."),
    ("separate", "Ajratmoq", "/ˈsep.ər.eɪt/", "Separate recycling from household trash."),
    ("serve", "Xizmat ko'rsatmoq, tortmoq", "/sɜːv/", "Restaurants serve traditional Uzbek meals."),
    ("share", "Ulashmoq, baham ko'rmoq", "/ʃeə/", "Share your study notes with classmates."),
    ("solve", "Yechmoq, hal etmoq", "/sɒlv/", "Puzzles help train your logic to solve problems."),
    ("specify", "Aniq ko'rsatmoq", "/ˈspes.ɪ.faɪ/", "Specify your preferred test center location."),
    ("spend", "Sarflamoq (vaqt, pul)", "/spend/", "Spend thirty minutes reading every day."),
    ("statement", "Bayanot, da'vo", "/ˈsteɪt.mənt/", "Read the problem statement carefully."),
    ("suggest", "Taklif etmoq", "/səˈdʒest/", "I suggest making a weekly revision timetable."),
    ("summarize", "Xulosa qilmoq", "/ˈsʌm.ər.aɪz/", "Summarize the reading passage in three sentences."),
    ("support", "Qo'llab-quvvatlamoq", "/səˈpɔːt/", "Families support student learning."),
    ("surround", "O'rab olmoq", "/səˈraʊnd/", "Beautiful gardens surround the historic palace."),
    ("survive", "Yashab qolmoq", "/səˈvaɪv/", "Plants survive drought by storing water."),
    ("suspect", "Shubhalanmoq", "/səˈspekt/", "Detectives suspect the evidence was altered."),
    ("transform", "Tubdan o'zgartirmoq", "/trænsˈfɔːm/", "Education transforms lives and communities."),
    ("translate", "Tarjima qilmoq", "/trænsˈleɪt/", "Translate words into your native language."),
    ("understand", "Tushunmoq", "/ˌʌn.dəˈstænd/", "Do you understand the main thesis?"),
    ("value", "Qadrlamoq", "/ˈvæl.juː/", "Value your time and stay focused."),
    ("vary", "O'zgarib turmoq", "/ˈveə.ri/", "Prices vary depending on the season."),
    ("view", "Qaramoq, kuzatmoq", "/vjuː/", "View sample answers on the portal."),
    ("visit", "Tashrif buyurmoq", "/ˈvɪz.ɪt/", "Visit historic museums in Samarkand."),
    ("warn", "Ogohlantirmoq", "/wɔːn/", "Signs warn drivers of slippery roads."),
    ("waste", "Isrof qilmoq", "/weɪst/", "Do not waste precious study hours on games."),
    ("welcome", "Kutib olmoq", "/ˈwel.kəm/", "Teachers welcome new international students."),
    ("wonder", "Hayron bo'lmoq, ajablanmoq", "/ˈwʌn.də/", "I wonder what the test questions will be."),
    ("worry", "Tashvishlanmoq", "/ˈwʌr.i/", "Do not worry; practice builds confidence."),

    # Additional Essential Everyday Vocabulary (A1-A2)
    ("animal", "Hayvon, jonzot", "/ˈæn.ɪ.məl/", "The zoo is home to many rare animals."),
    ("apple", "Olma", "/ˈæp.əl/", "I eat a fresh green apple every morning."),
    ("artist", "Rassom, san'atkor", "/ˈɑː.tɪst/", "The artist painted a beautiful mountain portrait."),
    ("backpack", "Rukzak, orqa sumka", "/ˈbæk.pæk/", "Pack your books and water bottle in your backpack."),
    ("baker", "Novvoy, pishiriqchi", "/ˈbeɪ.kə/", "The local baker bakes hot fresh bread every morning."),
    ("ball", "Koptok, to'p", "/bɔːl/", "Children love playing with a soccer ball in the park."),
    ("banker", "Bank xodimi", "/ˈbæŋ.kə/", "She consults a banker about opening a savings account."),
    ("barber", "Sartosh, erkaklar sartoshi", "/ˈbɑː.bə/", "He gets a haircut at the barber shop every month."),
    ("beach", "Plyaj, dengiz bo'yi", "/biːtʃ/", "We spent a sunny day relaxing at the sandy beach."),
    ("bear", "Aiq, ayiq", "/beə/", "Brown bears live in mountain forests."),
    ("bed", "Krovat, o'rin-joy", "/bed/", "Make your bed right after waking up in the morning."),
    ("bell", "Qo'ng'iroq", "/bel/", "The school bell rings at eight in the morning."),
    ("bird", "Qush", "/bɜːd/", "Early morning birds sing in the trees."),
    ("bookstore", "Kitob do'koni", "/ˈbʊk.stɔː/", "We bought dictionary references at the bookstore."),
    ("bottle", "Idish, shisha, baklashka", "/ˈbɒt.əl/", "Always carry a reusable water bottle to class."),
    ("bread", "Non", "/bred/", "Fresh Uzbek non bread goes great with warm tea."),
    ("bridge", "Ko'prik", "/brɪdʒ/", "Vehicles cross the wide river over the concrete bridge."),
    ("broom", "Supurgi", "/bruːm/", "Use the broom to sweep the kitchen floor."),
    ("brother", "Aka, uka", "/ˈbrʌð.ə/", "My elder brother is an electrical engineer."),
    ("brush", "Cho'tka, tish cho'tkasi", "/brʌʃ/", "Brush your teeth twice a day for good health."),
    ("building", "Bino, imorat", "/ˈbɪl.dɪŋ/", "The university library is an impressive modern building."),
    ("bus stop", "Avtobus bekat", "/ˈbʌs stɒp/", "Wait for the morning bus at the bus stop."),
    ("butter", "Sariq yog'", "/ˈbʌt.ə/", "Spread butter on toast for breakfast."),
    ("cake", "Tort, pirog", "/keɪk/", "They baked a chocolate cake for her birthday."),
    ("camera", "Fotoaparat, kamera", "/ˈkæm.rə/", "Take photos of historic places with a digital camera."),
    ("candle", "Sham", "/ˈkæn.dəl/", "Lighting candles created a peaceful mood."),
    ("capital", "Poytaxt", "/ˈkæp.ɪ.təl/", "Tashkent is the capital city of Uzbekistan."),
    ("car", "Avtomobil, mashina", "/kɑː/", "Electric cars emit zero pollution in cities."),
    ("carpet", "Gilam", "/ˈkɑː.pɪt/", "Uzbek handmade carpets have intricate patterns."),
    ("carrot", "Sabzi", "/ˈkær.ət/", "Carrots are rich in vitamins for good vision."),
    ("cat", "Mushuk", "/kæt/", "The furry cat slept peacefully near the window."),
    ("chair", "Stul, o'rindiq", "/tʃeə/", "Sit comfortably on the ergonomic study chair."),
    ("cheese", "Plo'r, pishloq", "/tʃiːz/", "Add cheese to your sandwich for lunch."),
    ("chef", "Oshpaz", "/ʃef/", "The chef prepared a special meal for hotel guests."),
    ("chicken", "Tovuq go'shti", "/ˈtʃɪk.ɪn/", "Grilled chicken salad is a nutritious dinner option."),
    ("child", "Bola", "/tʃaɪld/", "Every child deserves quality primary education."),
    ("church", "Cherkov", "/tʃɜːtʃ/", "Historic churches display majestic architecture."),
    ("cinema", "Kinoteatr", "/ˈsɪn.ə.mɑː/", "We watched an action movie at the local cinema."),
    ("circle", "Doira, aylana", "/ˈsɜː.kəl/", "Students stood in a wide circle during physical education."),
    ("clock", "Soat (devor soati)", "/klɒk/", "The wall clock showed ten minutes to nine."),
    ("coat", "Palto, ustki kiyim", "/kəʊt/", "Put on a thick coat before going out in snow."),
    ("coffee", "Kofe", "/ˈkɒf.i/", "A cup of hot coffee helps stay awake while studying."),
    ("coin", "Tanga, pul", "/kɔɪn/", "Insert a coin into the vending machine to buy water."),
    ("cold", "Sovuq", "/kəʊld/", "Drink warm herbal tea when the weather turns cold."),
    ("cook", "Oshpazlik qilmoq, taom pishirmoq", "/kʊk/", "My mother cooks delicious meals for our family."),
    ("corner", "Burchak, burilish", "/ˈkɔː.nə/", "The bakery is located right on the street corner."),
    ("country", "Mamlakat, yurt", "/ˈkʌn.tri/", "Uzbekistan is a beautiful Central Asian country."),
    ("cow", "Sigir", "/kaʊ/", "Farmers collect fresh milk from dairy cows."),
    ("cup", "Piyola, finjon", "/kʌp/", "Pour hot tea into a ceramic cup."),
    ("daughter", "Qiz farzand", "/ˈdɔː.tə/", "Their daughter studies law at the university."),
    ("desk", "Yozuv stoli, parta", "/desk/", "Keep your study desk organized and tidy."),
    ("doctor", "Shifokor, doktor", "/ˈdɒk.tə/", "The doctor examined the patient thoroughly."),
    ("dog", "It", "/dɒɡ/", "The loyal dog guarded the house at night."),
    ("door", "Eshik", "/dɔː/", "Remember to lock the front door when leaving."),
    ("dress", "Ko'ylak (ayollar kiyimi)", "/dres/", "She wore an elegant dress to the graduation evening."),
    ("driver", "Haydovchi", "/ˈdraɪ.və/", "The bus driver drove safely through rain."),
    ("ear", "Quloq", "/ɪə/", "Wear headphones to listen to English podcasts clearly."),
    ("earth", "Yer shar, zamin", "/ɜːθ/", "The Earth revolves around the Sun in space."),
    ("egg", "Tuxum", "/eɡ/", "Boiled eggs provide healthy protein for breakfast."),
    ("elephant", "Fil", "/ˈel.ɪ.fənt/", "Elephants are the largest living land animals."),
    ("engineer", "Muhandis, inzhener", "/ˌen.dʒɪˈnɪə/", "The software engineer created an innovative application."),
    ("eye", "Ko'z", "/aɪ/", "Protect your eyes when working long hours at screens."),
    ("face", "Yuz, bashara", "/feɪs/", "Wash your face with cold water to refresh yourself."),
    ("family", "Oila", "/ˈfæm.əl.i/", "Family support is a foundation for personal growth."),
    ("farm", "Fermer xo'jaligi, ferma", "/fɑːm/", "The farm produces organic fresh vegetables."),
    ("father", "Ota", "/ˈfɑː.ðə/", "My father taught me the importance of hard work."),
    ("finger", "Barmoq (qo'l barmog'i)", "/ˈfɪŋ.ɡə/", "Point with your index finger to select options."),
    ("fire", "Olov, yong'in", "/faɪə/", "Firefighters extinguished the fire quickly."),
    ("fish", "Baliq", "/fɪʃ/", "Fresh fish contains omega-3 fatty acids."),
    ("flag", "Bayroq", "/flæɡ/", "The national flag floated proudly in the breeze."),
    ("flower", "Gul", "/ˈflaʊ.ə/", "Spring flowers bloom brightly in public parks."),
    ("food", "Taom, ovqat", "/fuːd/", "Healthy food gives you stamina for learning."),
    ("foot", "Oyoq (kaft qismi)", "/fʊt/", "We walked to school on foot every morning."),
    ("forest", "O'rmon", "/ˈfɒr.ɪst/", "Dense pine forests cover the mountain slope."),
    ("fork", "Sanchqi, vilka", "/fɔːk/", "Use a fork and knife when eating dinner."),
    ("friend", "Do'st, o'rtoq", "/frend/", "True friends encourage each other's dreams."),
    ("fruit", "Meva", "/fruːt/", "Eat fresh seasonal fruit for vitamins."),
    ("garden", "Bog', hovli", "/ˈɡɑː.dən/", "They plant roses and tulips in their garden."),
    ("glass", "Stakan, oyna", "/ɡlɑːs/", "Drink a full glass of water every morning."),
    ("glasses", "Ko'zoynak", "/ˈɡlɑːs.ɪz/", "He wears reading glasses to study textbooks."),
    ("glove", "Qo'lqop", "/ɡlʌv/", "Wear warm gloves in snowy winter weather."),
    ("goat", "Echki", "/ɡəʊt/", "Mountain goats climb steep rocky cliffs effortlessly."),
    ("grass", "O't, maysazor", "/ɡrɑːs/", "Children love playing on the green park grass."),
    ("hair", "Soch", "/heə/", "She combed her long brown hair before leaving."),
    ("hand", "Qo'l (kaft)", "/hænd/", "Raise your hand if you know the correct answer."),
    ("hat", "Shapka, qalpoq", "/hæt/", "Wear a sun hat when walking outdoors in summer."),
    ("head", "Bosh, kalla", "/hed/", "Tilt your head slightly when focusing on listening."),
    ("heart", "Yurak", "/hɑːt/", "Regular cardio exercise keeps your heart healthy."),
    ("horse", "Ot", "/hɔːs/", "Riding horses is a popular traditional activity."),
    ("hospital", "Kasalxona", "/ˈhɒs.pɪ.təl/", "The modern city hospital treats emergency patients."),
    ("hotel", "Mehmonxona", "/həʊˈtel/", "Tourists booked rooms at a comfortable hotel."),
    ("house", "Uy, hovli", "/haʊs/", "They built a spacious house near the river."),
    ("husband", "Turmush o'rtoq, er", "/ˈhʌz.bənd/", "Her husband works as an architectural designer."),
    ("ice", "Muz", "/aɪs/", "Put ice cubes in your lemonade to cool down."),
    ("ice cream", "Muzqaymoq", "/ˌaɪs ˈkriːm/", "Children enjoy vanilla ice cream in summer."),
    ("island", "Orol", "/ˈaɪ.lənd/", "Tropical islands are famous for palm trees and beaches."),
    ("jacket", "Kurtka, nimcha", "/ˈdʒæk.ɪt/", "Wear a leather jacket on chilly autumn days."),
    ("job", "Ish, mehnat", "/dʒɒb/", "Finding a rewarding job requires skills and practice."),
    ("juice", "Sharbat, sroq", "/dʒuːs/", "Fresh orange juice is rich in vitamin C."),
    ("key", "Kalit", "/kiː/", "Keep your house keys in a safe pocket."),
    ("kitchen", "Oshxona", "/ˈkɪtʃ.ən/", "The kitchen is equipped with a modern oven."),
    ("knife", "Pichoq", "/naɪf/", "Be careful when using a sharp knife to cut vegetables."),
    ("lake", "Ko'l", "/leɪk/", "People go boating on the serene mountain lake."),
    ("lamp", "Lampa, chiroq", "/læmp/", "Turn on the desk lamp when studying at night."),
    ("leg", "Oyoq", "/leɡ/", "Stretch your legs after sitting for forty minutes."),
    ("library", "Kutubxona", "/ˈlaɪ.brər.i/", "Students read quietly in the university library."),
    ("light", "Yorug'lik, yengil", "/laɪt/", "Natural daylight flows through the wide windows."),
    ("lion", "Sher, arslon", "/ˈlaɪ.ən/", "Lions are majestic wild cats living in African savannas."),
    ("lunch", "Tushlik, tushlik taom", "/lʌntʃ/", "We meet at the canteen for lunch at one PM."),
    ("market", "Bozor", "/ˈmɑː.kɪt/", "Chorsu Bazaar is a famous historic market in Tashkent."),
    ("meat", "Go'sht", "/miːt/", "Uzbek cuisine features grilled meat skewers called shashlik."),
    ("milk", "Sut", "/mɪlk/", "Drink a warm glass of milk before bedtime."),
    ("money", "Pul", "/ˈmʌn.i/", "Manage your monthly pocket money wisely."),
    ("monkey", "Maymun", "/ˈmʌŋ.ki/", "Monkeys swing agilely through jungle trees."),
    ("moon", "Oy (tungi)", "/muːn/", "The full moon shines brightly in the clear night sky."),
    ("mother", "Ona", "/ˈmʌð.ə/", "My mother prepares delicious home-cooked meals."),
    ("mountain", "Tog'", "/ˈmaʊn.tɪn/", "Tian Shan mountains offer breathtaking scenic views."),
    ("mouth", "Og'iz", "/maʊθ/", "Open your mouth clearly when pronouncing vowels."),
    ("museum", "Muzey", "/mjuːˈziː.əm/", "State history museums exhibit ancient Uzbek gold items."),
    ("music", "Musiqa", "/ˈmjuː.zɪk/", "Listening to classical music enhances study concentration."),
    ("neck", "Bo'yin", "/nek/", "Wear a wool scarf around your neck in winter."),
    ("needle", "Igna", "/ˈniː.dəl/", "Tailors use a fine needle and thread to sew clothes."),
    ("net", "To'r, setka", "/net/", "Fishermen throw woven nets into the river."),
    ("newspaper", "Gazeta", "/ˈnjuːzˌpeɪ.pə/", "He reads the morning newspaper during breakfast."),
    ("night", "Tun, kecha", "/naɪt/", "The stars twinkle brightly at night."),
    ("nose", "Burun", "/nəʊz/", "Breathe in deeply through your nose."),
    ("nurse", "Hamshira, tibbiy hamshira", "/nɜːs/", "The caring nurse measured the patient's temperature."),
    ("ocean", "Okean", "/ˈəʊ.ʃən/", "The Pacific Ocean covers a massive surface area."),
    ("office", "Ofis, idora", "/ˈɒf.ɪs/", "She works in a spacious modern downtown office."),
    ("oil", "Yog', moy", "/ɔɪl/", "Use olive oil for cooking healthy fresh salads."),
    ("orange", "Apelsin, apelsin rang", "/ˈɒr.ɪndʒ/", "Oranges are sweet, juicy, and rich in vitamin C."),
    ("paper", "Qog'oz", "/ˈpeɪ.pə/", "Write your daily ideas on a clean sheet of paper."),
    ("park", "Xiyobon, park", "/pɑːk/", "Families take evening walks in the green park."),
    ("pen", "Ruchka", "/pen/", "Always carry a blue ballpoint pen to exams."),
    ("pencil", "Qalam", "/ˈpen.səl/", "Use a graphite pencil to sketch design outlines."),
    ("person", "Inson, kishi", "/ˈpɜː.sən/", "Every person has unique talents and perspectives."),
    ("pet", "Uy hayvoni", "/pet/", "Cats and dogs are popular household pets."),
    ("phone", "Telefon", "/fəʊn/", "Silence your mobile phone during class lectures."),
    ("photo", "Fotosurat, rasm", "/ˈfəʊ.təʊ/", "They took a memorable group photo at graduation."),
    ("picture", "Rasm, tasvir", "/ˈpɪk.tʃə/", "Hang a landscape picture on the living room wall."),
    ("pilot", "Uchuvchi, pilot", "/ˈpaɪ.lət/", "The skilled pilot landed the aircraft safely."),
    ("plate", "Tarelka, idish", "/pleɪt/", "Serve warm plov on a large decorated ceramic plate."),
    ("police", "Militsiya, politsiya", "/pəˈliːs/", "Police officers maintain safety in the city."),
    ("park", "Istirohat bog'i", "/pɑːk/", "Children play on swings in the neighborhood park."),
    ("rain", "Yog'garachilik, yomg'ir", "/reɪn/", "Spring rain freshens the city air."),
    ("river", "Daryo", "/ˈrɪv.ə/", "The Syr Darya river flows through Central Asia."),
    ("road", "Yo'l, ko'cha", "/rəʊd/", "Drive carefully on wet asphalt roads."),
    ("roof", "Tosh, tom, tami", "/ruːf/", "Snow covered the roofs of houses in winter."),
    ("room", "Xona", "/ruːm/", "My study room is quiet and well-lit."),
    ("rose", "Atirgul", "/rəʊz/", "Red roses bloom in the flower garden."),
    ("salt", "Tuz", "/sɒlt/", "Add a pinch of salt to season the soup."),
    ("sandwich", "Buterbrod, sendvich", "/ˈsæn.wɪdʒ/", "He packed a cheese sandwich for lunch."),
    ("school", "Maktab", "/skuːl/", "Children attend primary school for basic education."),
    ("sea", "Dengiz", "/siː/", "Ships sail across the Mediterranean Sea."),
    ("shoe", "Poyabzal, tufli", "/ʃuː/", "Tie your shoe laces securely before running."),
    ("shop", "Do'kon", "/ʃɒp/", "Buy fresh bread at the neighborhood bakery shop."),
    ("sister", "Opa, singil", "/ˈsɪs.tə/", "My younger sister studies medicine at university."),
    ("sky", "Osmon, falak", "/skaɪ/", "The blue sky was clear with no clouds."),
    ("snow", "Qor", "/snəʊ/", "Children build snowmen when it snows in winter."),
    ("sofa", "Divan", "/ˈsəʊ.fə/", "Relax on the soft sofa after a long day."),
    ("son", "O'g'il farzand", "/sʌn/", "Their son won the school math olympiad."),
    ("soup", "Sho'rva, moshxo'rda", "/suːp/", "Hot vegetable soup is comforting on cold days."),
    ("spoon", "Qoshiq", "/spuːn/", "Use a soup spoon to eat hot noodle soup."),
    ("star", "Yulduz", "/stɑː/", "Millions of stars illuminate the desert sky."),
    ("station", "Bekat, stantsiya", "/ˈsteɪ.ʃən/", "The train departs from Tashkent Central Station."),
    ("street", "Ko'cha", "/striːt/", "Trees line both sides of the quiet residential street."),
    ("student", "Talaba, o'quvchi", "/ˈstjuː.dənt/", "Every student strives for academic progress."),
    ("sugar", "Shakar", "/ˈʃʊɡ.ə/", "Do you take sugar in your morning black tea?"),
    ("sun", "Quyosh", "/sʌn/", "The sun rises in the east every morning."),
    ("table", "Stol", "/ˈteɪ.bəl/", "Place your study textbooks neatly on the table."),
    ("taxi", "Taksi", "/ˈtæk.si/", "Take a taxi to reach the airport quickly."),
    ("tea", "Choy", "/tiː/", "Uzbek green tea is served in traditional piala cups."),
    ("teacher", "O'qituvchi, ustoz", "/ˈtiː.tʃə/", "Our English teacher explains complex topics clearly."),
    ("telephone", "Telefon", "/ˈtel.ɪ.fəʊn/", "Answer the telephone when it rings."),
    ("time", "Vaqt", "/taɪm/", "Manage your study time effectively every day."),
    ("town", "Shahar, shaharcha", "/taʊn/", "Khiva is a historic Uzbek town with ancient walls."),
    ("tree", "Daraxt", "/triː/", "Fruit trees bloom with white flowers in spring."),
    ("trousers", "Shalvar, shim", "/ˈtraʊ.zəz/", "He wore dark trousers and a crisp white shirt."),
    ("uncle", "Toga, amaki", "/ˈʌŋ.kəl/", "My uncle lives in a quiet mountain village."),
    ("university", "Universitet, oliygoh", "/ˌjuː.nɪˈvɜː.sə.ti/", "She plans to study engineering at university."),
    ("vegetable", "Sabzavot", "/ˈvedʒ.tə.bəl/", "Fresh vegetables form the basis of a healthy diet."),
    ("village", "Qishloq, qishloq joy", "/ˈvɪl.ɪdʒ/", "Fresh air and quiet surroundings characterize the village."),
    ("wall", "Devor", "/wɔːl/", "Paint the bedroom walls with light calm colors."),
    ("watch", "Qo'l soati, tomosha qilmoq", "/wɒtʃ/", "Check your wrist watch for test timing."),
    ("water", "Suv", "/ˈwɔː.tə/", "Drinking clean water is essential for your body."),
    ("weather", "Ob-havo", "/ˈweð.ə/", "Spring weather in Tashkent is warm and pleasant."),
    ("wife", "Xotin, rafiqa", "/waɪf/", "His wife is a doctor at the children's hospital."),
    ("window", "Oyna, rom", "/ˈwɪn.dəʊ/", "Open the window to let fresh air into the room."),
    ("winter", "Qish fasli", "/ˈwɪn.tə/", "Snow covers mountain peaks during winter."),
    ("woman", "Ayol, xotin-qiz", "/ˈwʊm.ən/", "The inspiring woman led an international project."),
    ("writer", "Yozuvchi, adib", "/ˈraɪ.tə/", "The famous writer published a novel about Uzbekistan."),
    ("year", "Yil", "/jɪə/", "A new academic year starts in September.")
]

def generate_full_deck():
    cards = []
    seen = set()
    for word, back, phonetic, example in A1_A2_MASSIVE_DATABASE:
        w_cap = word.capitalize()
        if w_cap not in seen:
            seen.add(w_cap)
            cards.append({
                "front": w_cap,
                "back": back,
                "phonetic": phonetic,
                "example": example
            })

    print(f"Generated A1-A2 Total Unique Cards: {len(cards)}")
    return cards

def update_preset_decks():
    cards = generate_full_deck()
    
    with open("src/data/presetDecks.ts", "r", encoding="utf-8") as f:
        content = f.read()

    new_cards_json = json.dumps(cards, ensure_ascii=False, indent=16)

    content = re.sub(
        r"title:\s*'🌱 A1-A2 Starter Vocabulary[^']*'",
        f"title: '🌱 A1-A2 Starter Vocabulary ({len(cards)} Kartochka)'",
        content
    )

    pattern = r"(id:\s*'deck_starter_a1_a2'.*?cards:\s*)\[.*?\](\s*\},)"
    replacement = rf"\g<1>{new_cards_json}\g<2>"

    updated_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

    with open("src/data/presetDecks.ts", "w", encoding="utf-8") as f:
        f.write(updated_content)

    print("Successfully updated src/data/presetDecks.ts with massive A1-A2 deck!")

if __name__ == "__main__":
    update_preset_decks()
