import json
import re

A1_A2_FULL_DATABASE = [
    # Verbs
    ("accept", "Qabul qilmoq, rozi bo'lmoq", "/əkˈsept/", "She decided to accept the job offer in Tashkent."),
    ("achieve", "Erishmoq, qo'lga kiritmoq", "/əˈtʃiːv/", "She worked hard to achieve her target IELTS score."),
    ("allow", "Ruxsat bermoq, yo'l qo'ymoq", "/əˈlaʊ/", "The library allows students to borrow five books at a time."),
    ("appear", "Ko'rinmoq, paydo bo'lmoq", "/əˈpɪə/", "A rainbow appeared in the sky after the rain."),
    ("apply", "Hujjat topshirmoq, qo'llamoq", "/əˈplaɪ/", "I plan to apply for a university scholarship next month."),
    ("arrange", "Uushtirmoq, tartibga solmoq", "/əˈreɪndʒ/", "We need to arrange a meeting with the teacher tomorrow."),
    ("arrive", "Yetib kelmoq, kelmoq", "/əˈraɪv/", "The train will arrive at the station at six o'clock."),
    ("avoid", "Qochmoq, saqlanmoq", "/əˈvɔɪd/", "You should avoid eating unhealthy fast food every day."),
    ("become", "Bo'lmoq, aylanmoq", "/bɪˈkʌm/", "He worked hard and became a successful software engineer."),
    ("believe", "Ishoqmoq, ishonch bildirmoq", "/bɪˈliːv/", "I believe that consistent practice is key to success."),
    ("borrow", "Qarzga olmoq (vaqtinchalik)", "/ˈbɒr.əʊ/", "Can I borrow your English dictionary for ten minutes?"),
    ("celebrate", "Nishonlamoq, bayram qilmoq", "/ˈsel.ə.breɪt/", "My family gathers to celebrate Navruz every spring."),
    ("compare", "Taqqoslamoq, solishtirmoq", "/kəmˈpeə/", "Compare your answers with a partner to find mistakes."),
    ("complain", "Shikoyat qilmoq, norozi bo'lmoq", "/kəmˈpleɪn/", "Customers complain when the internet service is slow."),
    ("confirm", "Tasdiqlamoq, aniqlik kiritmoq", "/kənˈfɜːm/", "Please call the hotel to confirm your room reservation."),
    ("continue", "Davom ettirmoq, to'xtamaslik", "/kənˈtɪn.juː/", "We will continue our lesson after a short break."),
    ("create", "Yaratmoq, bino qilmoq", "/kriˈeɪt/", "Designers create innovative solutions for modern problems."),
    ("decide", "Qaror qilmoq, bir toxtamga kelmoq", "/dɪˈsaɪd/", "I must decide which subject to study first today."),
    ("describe", "Tasvirlamoq, ta'riflamoq", "/dɪˈskraɪb/", "Can you describe your hometown in three sentences?"),
    ("destroy", "Vayron qilmoq, yo'q qilmoq", "/dɪˈstrɔɪ/", "Heavy storms can destroy old wooden buildings."),
    ("discover", "Kashf etmoq, topmoq", "/dɪˈskʌv.ə/", "Scientists discover new plant species in tropical forests."),
    ("discuss", "Muhokama qilmoq, maslahatlashmoq", "/dɪˈskʌs/", "Let's discuss the project steps during lunch."),
    ("encourage", "Rag'batlantirmoq, ruhlantirmoq", "/ɪnˈkʌr.ɪdʒ/", "Teachers encourage students to ask creative questions."),
    ("explain", "Tushuntirmoq, izohlamoq", "/ɪkˈspleɪn/", "The tutor explained the grammar rule very clearly."),
    ("improve", "Rivojlantirmoq, yaxshilamoq", "/ɪmˈpruːv/", "Daily reading will improve your English vocabulary."),
    ("include", "O'z ichiga olmoq, kiritmoq", "/ɪnˈkluːd/", "The course fee includes all textbooks and study materials."),
    ("increase", "Oshirmoq, ko'paytirmoq", "/ɪnˈkriːs/", "The company plans to increase production next year."),
    ("inform", "Xabardor qilmoq, bildirmoq", "/ɪnˈfɔːm/", "Please inform us if your address changes."),
    ("invite", "Taklif qilmoq, chaqirmoq", "/ɪnˈvaɪt/", "They invited all their relatives to the wedding."),
    ("manage", "Boshqarmoq, uddalamoq", "/ˈmæn.ɪdʒ/", "She managed to finish the assignment before midnight."),
    ("notice", "Payqamoq, sezib qolmoq", "/ˈnəʊ.tɪs/", "Did you notice any change in his behavior today?"),
    ("obtain", "Qo'lga kiritmoq, olmoq", "/əbˈteɪn/", "You need to obtain a visa before traveling abroad."),
    ("offer", "Taklif etmoq, taqdim qilmoq", "/ˈɒf.ə/", "The company offered him a well-paid manager position."),
    ("perform", "Bajarmoq, ijro etmoq", "/pəˈfɔːm/", "Students perform speaking tests in pairs."),
    ("prepare", "Tayyorgarlik ko'rmoq", "/prɪˈpeə/", "I prepare for my IELTS examination every evening."),
    ("prevent", "Oldini olmoq, yo'l qo'ymaslik", "/prɪˈvent/", "Regular checkups help prevent health complications."),
    ("protect", "Himoya qilmoq, asramoq", "/prəˈtekt/", "We must protect our environment from toxic waste."),
    ("provide", "Ta'minlamoq, berish", "/prəˈvaɪd/", "Schools provide students with modern digital tools."),
    ("receive", "Qabul qilib olmoq, olmoq", "/rɪˈsiːv/", "I received an official acceptance letter this morning."),
    ("recommend", "Tavsiya qilmoq, maslahat bermoq", "/ˌrek.əˈmend/", "Doctors recommend sleeping at least eight hours a night."),
    ("reduce", "Kamaytirmoq, qisqartirmoq", "/rɪˈdjuːs/", "Recycling helps reduce pollution in big cities."),
    ("refuse", "Rad etmoq, ko'nmaslik", "/rɪˈfjuːz/", "He refused to sign the contract without reading it."),
    ("remember", "Eslamoq, yodda tutmoq", "/rɪˈmem.bə/", "Always remember to save your work before closing the window."),
    ("remove", "Olib tashlamoq, yo'qotmoq", "/rɪˈmuːv/", "Please remove your shoes before entering the room."),
    ("repair", "Tuzatmoq, ta'mirlamoq", "/rɪˈpeə/", "The mechanic will repair the car engine by afternoon."),
    ("replace", "Almashtirmoq, o'rnini bosmoq", "/rɪˈpleɪs/", "We need to replace the battery in the remote control."),
    ("require", "Talab qilmoq, ehtiyoj sezmoq", "/rɪˈkwaɪə/", "Passing the examination requires dedication and focus."),
    ("search", "Qidirmoq, izlamoq", "/sɜːtʃ/", "I spent an hour searching for my missing keys."),
    ("suggest", "Taklif bildirmoq, maslahat moq", "/səˈdʒest/", "I suggest revising new words before going to bed."),
    ("support", "Qo'llab-quvvatlamoq", "/səˈpɔːt/", "My family always supports my educational goals."),
    ("travel", "Sayohat qilmoq, yurmoq", "/ˈtræv.əl/", "Many young people love to travel across Central Asia."),
    ("understand", "Tushunmoq, uqmoq", "/ˌʌn.dəˈstænd/", "Do you understand the main idea of this listening track?"),

    # Nouns & Topics
    ("ability", "Qobiliyat, iqtidor", "/əˈbɪl.ə.ti/", "His ability to solve complex math problems is impressive."),
    ("accommodation", "Turar joy, yashash joyi", "/əˌkɒm.əˈdeɪ.ʃən/", "Finding affordable accommodation in London can be tricky."),
    ("activity", "Faoliyat, mashg'ulot", "/ækˈtɪv.ə.ti/", "Physical activity improves mental focus and wellbeing."),
    ("advantage", "Afzallik, ustunlik", "/ədˈvɑːn.tɪdʒ/", "Speed is the main advantage of rail transport."),
    ("advice", "Maslahat, o'git", "/ədˈvaɪs/", "My teacher gave me useful advice on writing essays."),
    ("agreement", "Kelishuv, shartnoma", "/əˈɡriː.mənt/", "Both countries signed a bilateral trade agreement."),
    ("amount", "Miqdor, summa", "/əˈmaʊnt/", "A large amount of money was raised for charity."),
    ("announcement", "E'lon, bildirishnoma", "/əˈnaʊns.mənt/", "Listen carefully to the flight announcement at the gate."),
    ("appointment", "Uchrashuv vaqti (shifokor, bank)", "/əˈpɔɪnt.mənt/", "I have a dentist appointment tomorrow morning."),
    ("arrangement", "Tashkillashtirish, kelishuv", "/əˈreɪndʒ.mənt/", "Flower arrangements decorated the dinner tables."),
    ("article", "Maqola, matn", "/ˈɑː.tɪ.kəl/", "I read an insightful article about artificial intelligence."),
    ("attention", "E'tibor, diqqat", "/əˈten.ʃən/", "Pay close attention to pronunciation details."),
    ("attitude", "Munosabat, qarash", "/ˈæt.ɪ.tʃuːd/", "A positive attitude helps overcome exam anxiety."),
    ("audience", "Auditoriya, tomoshabinlar", "/ˈɔː.di.əns/", "The speaker captivated the audience with great stories."),
    ("authority", "Vakolat, hokimiyat, nufuz", "/ɔːˈθɒr.ə.ti/", "Local authorities built a new public library."),
    ("average", "O'rtacha ko'rsatkich", "/ˈæv.ər.ɪdʒ/", "The average temperature in summer is thirty degrees."),
    ("behavior", "Xulq-atvor, yurish-turish", "/bɪˈheɪ.vjə/", "Good behavior is rewarded in elementary school."),
    ("benefit", "Foyda, naf, afzallik", "/ˈben.ɪ.fɪt/", "Exercise offers numerous health benefits."),
    ("business", "Biznes, tadbirkorlik", "/ˈbɪz.nɪs/", "She runs a successful online clothing business."),
    ("career", "Karyera, kasbiy yo'l", "/kəˈrɪə/", "He chose a career in software development."),
    ("cause", "Sabab, omil", "/kɔːz/", "Heavy rainfall was the main cause of the flooding."),
    ("celebration", "Bayram, nishonlash", "/ˌsel.əˈbreɪ.ʃən/", "The city organized a fireworks celebration on Independence Day."),
    ("challenge", "Qiyinchilik, chaqiriq", "/ˈtʃæl.ɪndʒ/", "Overcoming language barriers is a rewarding challenge."),
    ("chance", "Imkoniyat, omad", "/tʃɑːns/", "This is your chance to showcase your speaking skills."),
    ("choice", "Tanlov, ihtiyor", "/tʃɔɪs/", "Making the right career choice requires self-reflection."),
    ("community", "Jamiyat, hamjamiyat", "/kəˈmjuː.nə.ti/", "The local community built a neighborhood park."),
    ("company", "Kompaniya, korxona", "/ˈkʌm.pə.ni/", "She works for an international tech company."),
    ("condition", "Sharoit, ahvol", "/kənˈdɪʃ.ən/", "The living conditions in the village improved significantly."),
    ("confidence", "Ishonch, o'ziga ishonch", "/ˈkɒn.fɪ.dəns/", "Public speaking builds personal confidence."),
    ("consequence", "Oqibat, natija", "/ˈkɒn.sɪ.kwəns/", "Skipping classes has serious academic consequences."),
    ("decision", "Qaror", "/dɪˈsɪʒ.ən/", "Making a big life decision takes careful thought."),
    ("department", "Bo'lim, kafedra", "/dɪˈpɑːt.mənt/", "Contact the HR department for employment queries."),
    ("description", "Tavsif, ta'rif", "/dɪˈskrɪp.ʃən/", "Read the job description carefully before applying."),
    ("difference", "Farq, tafovut", "/ˈdɪf.ər.əns/", "There is a clear difference between spoken and written English."),
    ("direction", "Yo'nalish, yo'l-yo'riq", "/daɪˈrek.ʃən/", "Ask the police officer for directions to the museum."),
    ("disadvantage", "Kamchilik, salbiy tomon", "/ˌdɪs.ədˈvɑːn.tɪdʒ/", "Noise is a main disadvantage of living near airports."),
    ("discovery", "Kashfiyot", "/dɪˈskʌv.ər.i/", "The discovery of penicillin revolutionized medicine."),
    ("discussion", "Muhokama, muzokara", "/dɪˈskʌʃ.ən/", "We had a group discussion on climate policy."),
    ("distance", "Masofa, olislik", "/ˈdɪs.təns/", "The distance between Tashkent and Samarkand is 300 km."),
    ("education", "Ta'lim, ma'lumot", "/ˌedʒ.uˈkeɪ.ʃən/", "Quality education unlocks career opportunities."),
    ("effort", "Harakat, urinish", "/ˈef.ət/", "Learning a language requires continuous effort."),
    ("environment", "Atrof-muhit, ekologiya", "/ɪnˈvaɪ.rən.mənt/", "We must protect the natural environment."),
    ("equipment", "Asbob-uskuna, jihozlar", "/ɪˈkwɪp.mənt/", "The laboratory has state-of-the-art scientific equipment."),
    ("evidence", "Dalil, isbot", "/ˈev.ɪ.dəns/", "Police found clear evidence at the scene."),
    ("exercise", "Mashq, jismoniy mashg'ulot", "/ˈek.sə.saɪz/", "Daily physical exercise boosts energy levels."),
    ("experience", "Tajriba, hayotiy ko'nikma", "/ɪkˈspɪə.ri.əns/", "Hands-on work experience is valued by employers."),
    ("facility", "Inshoot, qulaylik, bino", "/fəˈsɪl.ə.ti/", "The university sport facility includes a swimming pool."),
    ("feature", "Xususiyat, ajralib turuvchi belgi", "/ˈfiː.tʃə/", "A touchscreen is a key feature of modern smartphones."),
    ("future", "Kelajak, istiqbol", "/ˈfjuː.tʃə/", "Investing in education secures a brighter future."),
    ("goal", "Maqsad, niyat", "/ɡəʊl/", "My primary goal is to score Band 7.5 in IELTS."),
    ("government", "Hukumat, davlat boshqaruvi", "/ˈɡʌv.ən.mənt/", "The government invested in renewable energy projects."),
    ("habit", "Odat, ko'nikma", "/ˈhæb.ɪt/", "Reading every night is a wonderful habit."),
    ("health", "Sog'liq, salomatlik", "/helθ/", "Good nutrition is crucial for maintain healthy health."),
    ("history", "Tarix", "/ˈhɪs.tər.i/", "Ancient Uzbek cities have a rich architectural history."),
    ("hobby", "Qiziqish, xobbi", "/ˈhɒb.i/", "Photography is my favorite creative hobby."),
    ("idea", "G'oya, fikr", "/aɪˈdɪə/", "She proposed a brilliant idea during the team brainstorming."),
    ("impact", "Ta'sir, kuchi", "/ˈɪm.pækt/", "Social media has a major impact on communication."),
    ("improvement", "Yaxshilanish, rivojlanish", "/ɪmˈpruːv.mənt/", "There is a noticeable improvement in your speaking fluency."),
    ("information", "Ma'lumot, axborot", "/ˌɪn.fəˈmeɪ.ʃən/", "The brochure provides useful tourist information."),
    ("instruction", "Yo'riqnoma, ko'rsatma", "/ɪnˈstrʌk.ʃən/", "Follow the assembly instructions step by step."),
    ("intention", "Niyat, maqsad", "/ɪnˈten.ʃən/", "It was not my intention to cause inconvenience."),
    ("interest", "Qiziqish, manfaat", "/ˈɪn.trest/", "She showed a keen interest in environmental science."),
    ("journey", "Sayohat, safar", "/ˈdʒɜː.ni/", "The train journey across the mountains was scenic."),
    ("knowledge", "Bilim, tushuncha", "/ˈnɒl.ɪdʒ/", "Practical knowledge is just as important as theory."),
    ("language", "Til", "/ˈlæŋ.ɡwɪdʒ/", "English is an international language of communication."),
    ("location", "Joylashuv, manzil", "/ləʊˈkeɪ.ʃən/", "The hotel is in an ideal downtown location."),
    ("management", "Boshqaruv, menejment", "/ˈmæn.ɪdʒ.mənt/", "Effective time management reduces study stress."),
    ("material", "Material, xomashyo, o'quv quroli", "/məˈtɪə.ri.əl/", "The course materials are available on the online portal."),
    ("meaning", "Ma'no, mazmun", "/ˈmiː.nɪŋ/", "Look up the meaning of unfamiliar words in a dictionary."),
    ("opportunity", "Imkoniyat", "/ˌɒp.əˈtʃuː.nə.ti/", "Internships offer a great opportunity to gain experience."),
    ("option", "Tanlov, varianti", "/ˈɒp.ʃən/", "You have the option to take the computer-based exam."),
    ("organization", "Tashkilot, tuzilma", "/ˌɔː.ɡən.aɪˈzeɪ.ʃən/", "The charity organization distributes food to families."),
    ("permission", "Ruxsat", "/pəˈmɪʃ.ən/", "Ask for permission before leaving the classroom."),
    ("personality", "Shaxsiyat, fe'l-atvor", "/ˌpɜː.sənˈæl.ə.ti/", "Her friendly personality makes her very popular."),
    ("population", "Aholi, xalq soni", "/ˌpɒp.jəˈleɪ.ʃən/", "The population of Tashkent exceeds three million people."),
    ("possibility", "Ehtimol, imkoniyat", "/ˌpɒs.əˈbɪl.ə.ti/", "There is a strong possibility of rain this weekend."),
    ("practice", "Amaliyot, mashq", "/ˈpræk.tɪs/", "Daily speaking practice is necessary for confidence."),
    ("preference", "Afzallik ko'rish, tanlov", "/ˈpref.ər.əns/", "State your accommodation preference on the registration form."),
    ("preparation", "Tayyorgarlik", "/ˌprep.ərˈeɪ.ʃən/", "Thorough preparation guarantees better test results."),
    ("problem", "Muammo, masala", "/ˈprɒb.ləm/", "Teamwork helps us solve difficult problems faster."),
    ("process", "Jarayon", "/ˈprəʊ.ses/", "Learning a new language is a gradual process."),
    ("product", "Mahsulot", "/ˈprɒd.ʌkt/", "The company launched an innovative tech product."),
    ("progress", "O'sish, ilgarilash", "/ˈprəʊ.ɡres/", "You are making steady progress in your studies."),
    ("purpose", "Maqsad, niyat", "/ˈpɜː.pəs/", "The main purpose of this meeting is to plan the event."),
    ("quality", "Sifat, daraja", "/ˈkwɒl.ə.ti/", "High quality customer service builds brand loyalty."),
    ("reason", "Sabab, vaji", "/ˈriː.zən/", "Explain the main reason for your choice in the essay."),
    ("relationship", "Munosabat, aloqa", "/rɪˈleɪ.ʃən.ʃɪp/", "Clear communication builds strong working relationships."),
    ("request", "Iltimos, so'rov", "/rɪˈkwest/", "Submit your vacation request two weeks in advance."),
    ("research", "Tadqiqot, izlanish", "/rɪˈsɜːtʃ/", "Scientists conduct research to find new cures."),
    ("resource", "Manba, resurs", "/rɪˈzɔːs/", "The library provides excellent online resources."),
    ("respect", "Hurmat, ehtirom", "/rɪˈspekt/", "Treating others with respect creates a positive climate."),
    ("responsibility", "Mas'uliyat, javobgarlik", "/rɪˌspɒn.sɪˈbɪl.ə.ti/", "Taking responsibility for your learning drives success."),
    ("result", "Natija", "/rɪˈzʌlt/", "The exam results will be announced next Monday."),
    ("safety", "Xavfsizlik", "/ˈseɪf.ti/", "Seatbelts are essential for car safety."),
    ("schedule", "Jadval, dars rejasi", "/ˈʃed.juːl/", "Check your daily study schedule on the dashboard."),
    ("science", "Fan, ilm-fan", "/ˈsaɪ.əns/", "Medical science has advanced dramatically over the decades."),
    ("skill", "Ko'nikma, mahorat", "/skɪl/", "Writing and speaking are key language skills."),
    ("society", "Jamiyat", "/səˈsaɪ.ə.ti/", "Education plays a vital role in modern society."),
    ("solution", "Yechim", "/səˈluː.ʃən/", "We found a simple solution to the technical problem."),
    ("source", "Manba, kelib chiqishi", "/sɔːs/", "Clean water is a vital natural resource and source of health."),
    ("strategy", "Strategiya, harakat rejasi", "/ˈstræt.ə.dʒi/", "A good study strategy helps you manage test time."),
    ("structure", "Tuzilma, struktura", "/ˈstrʌk.tʃə/", "Organize your essay with a logical paragraph structure."),
    ("success", "Muvaffaqiyat, yutuq", "/səkˈses/", "Hard work and consistency lead to academic success."),
    ("suggestion", "Taklif, maslahat", "/səˈdʒes.tʃən/", "Thank you for your valuable feedback and suggestions."),
    ("system", "Tizim, sistema", "/ˈsɪs.təm/", "Our online learning system updates grades automatically."),
    ("task", "Vazifa, topshiriq", "/tɑːsk/", "Complete your daily homework task before six PM."),
    ("technique", "Usul, texnika", "/tekˈniːk/", "Mind mapping is an effective memory technique."),
    ("technology", "Texnologiya", "/tekˈnɒl.ə.dʒi/", "Modern technology simplifies distance learning."),
    ("topic", "Mavzu, bo'lim", "/ˈtɒp.ɪk/", "Today's speaking topic is environmental conservation."),
    ("understanding", "Tushunish, anglash", "/ˌʌn.dəˈstæn.dɪŋ/", "Clear explanations deepen student understanding."),
    ("value", "Qiymat, qadr-qimmat", "/ˈvæl.juː/", "Education is a lifelong investment of immense value."),
    ("variety", "Xilma-xillik, turli-tumanlik", "/vəˈraɪ.ə.ti/", "The restaurant offers a wide variety of healthy salads."),

    # Adjectives
    ("accurate", "Aniq, to'g'ri", "/ˈæk.jə.rət/", "Ensure your answers are accurate before submitting."),
    ("active", "Faol, harakatchan", "/ˈæk.tɪv/", "Being active in class discussions improves fluency."),
    ("additional", "Qo'shimcha", "/əˈdɪʃ.ən.əl/", "You can find additional practice exercises online."),
    ("adequate", "Yetarli, mos", "/ˈæd.ə.kwət/", "Make sure you get adequate sleep before the exam."),
    ("advanced", "Ilg'or, yuqori darajadagi", "/ədˈvɑːnst/", "She attends an advanced English writing course."),
    ("amazing", "Ajoyib, hayratlanarli", "/əˈmeɪ.zɪŋ/", "The museum displayed an amazing collection of artifacts."),
    ("ancient", "Qadimiy, ko'xna", "/ˈeɪn.ʃənt/", "Samarkand is famous for its ancient historical monuments."),
    ("anxious", "Xavotirli, bezovta", "/ˈæŋk.ʃəs/", "Feeling anxious before a big test is completely normal."),
    ("appropriate", "Mos, munosib", "/əˈprəʊ.pri.ət/", "Wear appropriate formal clothing for the interview."),
    ("available", "Mavjud, bo'sh", "/əˈveɪ.lə.bəl/", "Study materials are available in the university library."),
    ("basic", "Asosiy, bazaviy", "/ˈbeɪ.sɪk/", "Mastering basic vocabulary is the first step in learning."),
    ("beneficial", "Foydali, manfaatlari", "/ˌben.ɪˈfɪʃ.əl/", "Reading daily is highly beneficial for language growth."),
    ("careful", "Ehtiyotkor, diqqatli", "/ˈkeə.fəl/", "Be careful when spelling complex technical terms."),
    ("certain", "Aniq, ishonchi komil", "/ˈsɜː.tən/", "I am certain that practice leads to improvement."),
    ("challenging", "Murakkab, qiyin lekin qiziq", "/ˈtʃæl.ɪn.dʒɪŋ/", "Solving advanced math logic is a challenging task."),
    ("comfortable", "Qulay, shinam", "/ˈkʌm.fə.tə.bəl/", "The new study chairs are ergonomic and comfortable."),
    ("common", "Keng tarqalgan, odatiy", "/ˈkɒm.ən/", "Spelling mistakes are common among beginner writers."),
    ("complete", "To'liq, mukammal", "/kəmˈpliːt/", "Make sure to give a complete answer to the question."),
    ("complex", "Murakkab, ko'p qirrali", "/ˈkɒm.pleks/", "Grammar structures become more complex at B2 level."),
    ("confident", "O'ziga ishonchi baland", "/ˈkɒn.fɪ.dənt/", "She felt confident during her speaking interview."),
    ("convenient", "Qulay, mos keladigan", "/kənˈviː.ni.ənt/", "Online learning provides a convenient study schedule."),
    ("creative", "Ijodkor, yaratuvchan", "/kriˈeɪ.tɪv/", "Writing essays encourages creative thinking."),
    ("crucial", "Hayotiy muhim, hal qiluvchi", "/ˈkruː.ʃəl/", "Time management is crucial for exam success."),
    ("cultural", "Madaniy, madaniyatga oid", "/ˈkʌl.tʃər.əl/", "Food is an integral part of cultural identity."),
    ("curious", "Qiziquvchan, bilishga intiluvchan", "/ˈkjʊə.ri.əs/", "Curious students learn faster by asking questions."),
    ("current", "Hozirgi, zamonaviy", "/ˈkʌr.ənt/", "Stay updated on current global news topics."),
    ("dangerous", "Xavfli, xatarli", "/ˈdeɪn.dʒər.əs/", "Driving without a seatbelt is extremely dangerous."),
    ("different", "Har xil, turlicha", "/ˈdɪf.ər.ənt/", "People have different learning preferences."),
    ("difficult", "Qiyin, murakkab", "/ˈdɪf.ɪ.kəlt/", "Pronouncing new sounds can be difficult at first."),
    ("disappointed", "Xafalangan, ko'ngli qolgan", "/ˌdɪs.əˈpɔɪn.tɪd/", "He felt disappointed after missing the target score."),
    ("effective", "Samarali, natijali", "/ɪˈfek.tɪv/", "Flashcards are an effective tool for memory building."),
    ("efficient", "Tejamkor, unumdor", "/ɪˈfɪʃ.ənt/", "An efficient study routine saves hours of effort."),
    ("essential", "Zarur, o'ta muhim", "/ɪˈsen.ʃəl/", "Hydration is essential during long study sessions."),
    ("excellent", "A'lo, mukammal", "/ˈek.səl.ənt/", "She scored an excellent result in reading."),
    ("expensive", "Qimmat, qimmatbaho", "/ɪkˈspen.sɪv/", "Studying abroad can be expensive without scholarships."),
    ("famous", "Mashhur, taniqli", "/ˈfeɪ.məs/", "Uzbekistan is famous for its hospitality and architecture."),
    ("fantastic", "Ajoyib, zo'r", "/fænˈtæs.tɪk/", "You did a fantastic job on your presentation!"),
    ("flexible", "Moslashuvchan, qayshqoq", "/ˈflek.sə.bəl/", "A flexible schedule allows working while studying."),
    ("friendly", "Do'stona, samimiy", "/ˈfrend.li/", "The tutors at the center are very warm and friendly."),
    ("generous", "Saxiy, qo'li ochiq", "/ˈdʒen.ər.əs/", "Our host was very generous and welcoming."),
    ("global", "Jahon miqyosidagi, global", "/ˈɡləʊ.bəl/", "Climate change is a urgent global issue."),
    ("grateful", "Minnatdor, tasakkur aytuvchi", "/ˈɡreɪt.fəl/", "I am grateful for the guidance of my mentors."),
    ("healthy", "Sog'lom, foydali", "/ˈhel.θi/", "Eating a healthy breakfast improves morning focus."),
    ("helpful", "Foydali, yordam beruvchi", "/ˈhelp.fəl/", "The textbook includes helpful grammar summaries."),
    ("honest", "Halol, to'g'riso'z", "/ˈɒn.ɪst/", "Honest self-assessment is key to identifying weaknesses."),
    ("huge", "Juda katta, ulkan", "/hjuːdʒ/", "Technology has made a huge difference in education."),
    ("important", "Muhim, ahamiyatli", "/ɪmˈpɔː.tənt/", "Consistency is the most important part of learning."),
    ("impossible", "Imkonsiz, ilojsiz", "/ɪmˈpɒs.ə.bəl/", "Nothing is impossible with dedication and practice."),
    ("independent", "Mustaqil, erkin", "/ˌɪn.dɪˈpen.dənt/", "Autonomous learning builds independent thinking."),
    ("intelligent", "Aqlli, zukkosi", "/ɪnˈtel.ɪ.dʒənt/", "She gave an intelligent analysis of the essay prompt."),
    ("international", "Xalqaro", "/ˌɪn.təˈnæʃ.ən.əl/", "IELTS is an international English language test."),
    ("necessary", "Zarur, kerakli", "/ˈnes.ə.ser.i/", "Regular revision is necessary for vocabulary retention."),
    ("obvious", "Aniq, ravshan, ko'rinib turgan", "/ˈɒb.vi.əs/", "There is an obvious link between practice and fluency."),
    ("official", "Rasmiy", "/əˈfɪʃ.əl/", "You will receive an official certificate after completing."),
    ("ordinary", "Oddiy, odatiy", "/ˈɔː.dən.ri/", "It was just an ordinary weekday morning."),
    ("original", "Asl, nusxa emas", "/əˈrɪdʒ.ən.əl/", "Always try to express original ideas in your essays."),
    ("particular", "Aynan bir, maxsus", "/pəˈtɪk.jə.lə/", "Is there any particular topic you want to discuss?"),
    ("patient", "Sabrli, chidamli", "/ˈpeɪ.ʃənt/", "Be patient with yourself when learning a new language."),
    ("polite", "Xushmuomala, odobli", "/pəˈlaɪt/", "Using polite language is important in speaking tests."),
    ("popular", "Ommabop, mashhur", "/ˈpɒp.jə.lə/", "Football is the most popular sport among students."),
    ("positive", "Ijobiy, yaxshi", "/ˈpɒz.ə.tɪv/", "Maintain a positive mindset during exam prep."),
    ("possible", "Imkoni bor, ehtimolli", "/ˈpɒs.ə.bəl/", "It is possible to master vocabulary with daily flashcards."),
    ("practical", "Amaliy, foydali", "/ˈpræk.tɪ.kəl/", "Focus on learning practical words used in daily life."),
    ("precious", "Qimmatbaho, qadrli", "/ˈpreʃ.əs/", "Time is your most precious study resource."),
    ("regular", "Muntazam, doimiy", "/ˈreɡ.jə.lə/", "Establish a regular study routine for best results."),
    ("reliable", "Ishonchli", "/rɪˈlaɪ.ə.bəl/", "This online dictionary is a reliable reference source."),
    ("responsible", "Mas'uliyatli", "/rɪˈspɒn.sə.bəl/", "Students are responsible for tracking their own goals."),
    ("satisfied", "Qoniqqan, mamnun", "/ˈsæt.ɪs.faɪd/", "She felt satisfied with her test score."),
    ("serious", "Jiddiy, muhim", "/ˈsɪə.ri.əs/", "Atmospheric pollution is a serious environmental threat."),
    ("similar", "O'xshash, hamrang", "/ˈsɪm.ɪ.lə/", "Synonyms are words with similar meanings."),
    ("simple", "Oddiy, oson", "/ˈsɪm.pəl/", "Keep your sentence structure clear and simple."),
    ("special", "Maxsus, alohida", "/ˈspeʃ.əl/", "The school organized a special ceremony for graduates."),
    ("specific", "Aniq, tayinli", "/spəˈsɪf.ɪk/", "Give specific examples to support your essay points."),
    ("suitable", "Mos, munosib", "/ˈsuː.tə.bəl/", "Choose a study environment suitable for quiet focus."),
    ("traditional", "An'anaviy, milliy", "/trəˈdɪʃ.ən.əl/", "Plov is a delicious traditional Uzbek dish."),
    ("typical", "Xarakterli, odatiy", "/ˈtɪp.ɪ.kəl/", "A typical study session lasts for forty-five minutes."),
    ("unique", "Yagona, takrorsiz", "/juːˈniːk/", "Every student has a unique learning pace."),
    ("useful", "Foydali, keragiga yaraydigan", "/ˈjuːs.fəl/", "This vocabulary list is extremely useful for beginners."),
    ("valuable", "Qimmatli, g'animat", "/ˈvæl.jə.bəl/", "Mock tests provide valuable practice for the real exam."),
    ("various", "Turli xil, har xil", "/ˈveə.ri.əs/", "The library contains books on various academic subjects."),
    ("vital", "Hayotiy muhim", "/ˈvaɪ.təl/", "Water is vital for maintaining physical health.")
]

def generate_a1_a2_cards():
    cards = []
    for word, back, phonetic, example in A1_A2_FULL_DATABASE:
        cards.append({
            "front": word.capitalize(),
            "back": back,
            "phonetic": phonetic,
            "example": example
        })

    print(f"Total curated A1-A2 Starter Cards: {len(cards)}")
    return cards

def update_preset_decks_ts():
    cards = generate_a1_a2_cards()
    
    # Read presetDecks.ts
    with open("src/data/presetDecks.ts", "r", encoding="utf-8") as f:
        content = f.read()

    # Replace deck_starter_a1_a2 cards
    new_cards_json = json.dumps(cards, ensure_ascii=False, indent=16)

    # Replace title to indicate exact count
    content = re.sub(
        r"title:\s*'🌱 A1-A2 Starter Vocabulary[^']*'",
        f"title: '🌱 A1-A2 Starter Vocabulary ({len(cards)} Kartochka)'",
        content
    )

    pattern = r"(id:\s*'deck_starter_a1_a2'.*?cards:\s*)\[.*?\](\s*\},)"
    replacement = rf"\g<1>{new_cards_json}\g<2>"

    updated_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

    with open("src/data/presetDecks.ts", "w", encoding="utf-8") as f:
        f.write(updated_content)

    print("Updated src/data/presetDecks.ts successfully!")

if __name__ == "__main__":
    update_preset_decks_ts()
