import re, json

n1_grammar_rules = [
    ("〜を余儀なくされる (wo yoginakusareru)", "wo yoginakusareru", "kutilmagan sharoit sababli majbur bo'lmoq / chora qolmaslik", "Ot + を余儀なくされる", "台風[たいふう]のため、計画[けいかく]の変更[へんこう]を余儀[よぎ]なくされた。", "Taifu no tame, keikaku no henkou wo yoginakusareta.", "Tayfun sababli rejani o'zgartirishga majbur bo'lindi."),
    ("〜てやまない (te yamanai)", "te yamanai", "chin dildan / samimiy tilamoq (to'xtovsiz)", "Fe'l (Te-form) + やまない", "皆様[みなさま]の健康[けんこう]とご多幸[たこう]を祈[いの]ってやみません。", "Minasama no kenkou to gotakou wo inotte yamamisen.", "Barchangizga sihat-salomatlik va baxt-saodat tilab qolaman."),
    ("〜を皮切りに (wo kawakiri ni)", "wo kawakiri ni", "...-dan boshlab ketma-ket hodisalar yuz bermoq", "Ot + を皮切りに", "東京[とうきょう]公演[こうえん]を皮切[かわき]りに、全国[ぜんこく]ツアーが始[はじ]まる。", "Toukyou kouen wo kawakiri ni, zenkoku tsuaa ga hajimaru.", "Tokio konsertidan boshlab, butun mamlakat bo'ylab turne boshlanadi."),
    ("〜をもって (wo motte)", "wo motte", "... bilan / ... sana bilan rasman yakunlanadi", "Ot + ををもって", "本日[ほんじつ]をもって、今年[ことし]の営業[えいぎょう]を終了[しゅうりょう]いたします。", "Honjitsu wo motte, kotoshi no eigyou wo shuuryou itashimasu.", "Bugungi kun bilan bu yilgi faoliyatimizni rasman yakunlaymiz."),
    ("〜ばこそ (ba koso)", "ba koso", "aynan o'sha sabab bo'lgani uchungina (boshqa sabab emas)", "Fe'l (Ba-form) / Sifat + ばこそ", "愛[あい]していればこそ、厳[きび]しく叱[しか]るのだ。", "Aishite ireba koso, kibishiku shikaru noda.", "Yaxshi ko'rganim uchungina qattiq urishaman."),
    ("〜がてら (gatera)", "gatera", "... qilish bahonasida bir yo'la ... ham qilmoq", "Fe'l (Masu-ildiz) / Ot + がてら", "散歩[さんぽ]がてら、本屋[ほんや]に行ってくる。", "Sanpo gatera, hon'ya ni itte kuru.", "Aylanish bahonasida bir yo'la kitob do'koniga borib kelaman."),
    ("〜かたがた (katagata)", "katagata", "... munosabati bilan bir vaqtda (Rasmiy)", "Ot + かたがた", "お礼[れい]かたがた、ご挨拶[あいさつ]に伺[うかが]いました。", "Orei katagata, goaisatsu ni伺imashita.", "Minnatdorchilik bildirish munosabati bilan ko'rishgani keldim."),
    ("〜にかかわる (ni kakawaru)", "ni kakawaru", "shaxsiyati / hayoti / obro'siga daxldor muhim masala", "Ot + にかかわる", "名誉[めいよ]にかかわる問題[もんだい]だから、黙[だま]っていられない。", "Meiyo ni kakawaru mondai dakara, damatte irarenai.", "Bu obro'ga daxldor masala bo'lgani uchun jim tura olmayman."),
    ("〜と相まって (to aimatte)", "to aimatte", "... bilan birgalikda yanada kuchaymoq", "Ot + と相まって", "努力[どりょく]と運[うん]が相[あい]まって、成功[せいこう]を収[おさ]めた。", "Doryoku to un ga aimatte, seikou wo osameta.", "Mehnat va omad birgalikda muvaffaqiyat keltirdi."),
    ("〜をおいて (wo oite)", "wo oite", "...-dan boshqa munosib nomzod umuman yo'q", "Ot + をおいて（ほかにない）", "この仕事[しごと]を任[まか]せられるのは、彼[かれ]をおいてほかにいない。", "Kono shigoto wo makaserareru no wa, kare wo oite hoka ni inai.", "Bu ishni topshirishga undan boshqa munosib odam yo'q."),
    ("〜ならでは (naradewa)", "naradewa", "faqat va faqat ...-gagina xos bo'lgan ajoyib sifat", "Ot + ならではの", "京都[きょうと]ならではの伝統的[でんとうてき]な風景[ふうけい]", "Kyouto naradewa no dentouteki na fuukei", "Faqat Kioto shahrigagina xos bo me'moriy manzara"),
    ("〜なくしては (nakushite wa)", "nakushite wa", "... bo'lmasa iloji yo'q / amalga oshmaydi", "Ot + なくしては", "皆様[みなさま]の協力[きょうりょく]なくしては、成功[せいこう]し得[え]ない。", "Minasama no kyouryoku nakushite wa, seikou shienai.", "Sizlarning hamkorlingizsiz muvaffaqiyatga erishib bo'lmaydi."),
    ("〜たる者 (taru mono)", "taru mono", "... kabi yuksak mavqega ega bo'la turib", "Ot + たる者", "指導者[しどうしゃ]たる者、常[つね]に誠実[せいじつ]でなければならない。", "Shidousha taru mono, tsune ni seijitsu de nakereba naranai.", "Rahbar bo'lgan shaxs har doim halol bo'lishi shart."),
    ("〜ともなると (tomo naruto)", "tomo naruto", "... yuqori darajaga etganda shunday bo'ladi", "Ot + ともなると", "プロの選手[せんしゅ]ともなると、練習[れんしゅう]の質[しつ]が違[ちが]う。", "Puro no senshu tomo naruto, renshuu no shitsu ga chigau.", "Professional sportchi darajasiga etganda mashq sifati boshqacha bo'ladi."),
    ("〜まじき (majiki)", "majiki", "... qilish kasbga/axloqqa mutlaqo to'g me kelmaydi", "Fe'l (Lug'at) + まじき + Ot", "許[ゆる]すまじき行為[こうい]", "Yurusumajiki koui", "Kechirib bo'lmaydigan qilmish"),
    ("〜を限りに (wo kagiri ni)", "wo kagiri ni", "oxirgi marta / shu sana bilan tugaydi", "Ot + を限りに", "今日[きょう]を限[かぎ]りに、タバコをやめる。", "Kyou wo kagiri ni, tabako wo yameru.", "Bugun oxirgi kuni bo'lib, chekishni tashlayman."),
    ("〜を踏まえて (wo fumaete)", "wo fumaete", "... ma'lumotlar / tajribaga tayanib", "Ot + を踏まえて", "前回[ぜんかい]の反省[はんせい]を踏[ふ]まえて、改善[かいぜん]する。", "Zenkai no hansei wo fumaete, kaizen suru.", "O'tgan safargi xatolarni hisobga olib o'nglaymiz."),
    ("〜に照らして (ni terashite)", "ni terashite", "qonun va axloq me'yorlariga solishtirgan holda", "Ot + に照らして", "法律[ほうりつ]に照[て]らして、厳[きび]しく処罰[しょばつ]する。", "Houritsu ni terashite, kibishiku shobatsu suru.", "Qonunga solishtirgan holda qattiq jazolanadi."),
    ("〜に則って (ni norotto)", "ni norotto", "qoidalarga va an'analarga qat'iy amal qilib", "Ot + に則って", "伝統[でんとう]に則[のっと]って、儀式[ぎしき]を行[おこな]う。", "Dentou ni norotto, gishiki wo okonau.", "An'analarga qat'iy amal qilib marosim o'tkaziladi."),
    ("〜をものの (wo monono)", "wo monono", "... bo'lsa-da / shunday bo'lishiga qaramay", "Fe'l (Plain) + ものの", "免許[めんきょ]は取[と]ったものの、運転[うんてん]していない。", "Menkyo wa totta monono, unten shite inai.", "Guvohnoma olgan bo'lsam-da, mashina haydamayman."),
    ("〜に耐え得る (ni tae uru)", "ni tae uru", "...-shga loyiq / chiday oladigan", "Ot / Fe'l + に耐え得る", "鑑賞[かんしょう]に耐[た]え得[う]る作品[さくひん]", "Kanshou ni tae uru sakuhin", "Tomosha qilishga loyiq san'at asari"),
    ("〜を余儀なくさせる (wo yoginakusaseru)", "wo yoginakusaseru", "...-shga majbur qilmoq", "Ot + を余儀なくさせる", "不況[ふきょう]が企業[きぎょう]にリストラを余儀[よぎ]なくさせた。", "Fukyou ga kigyou ni risutora wo yoginakusaseta.", "Inqiroz kompaniyalarni qisqartirishga majbur qildi."),
    ("〜をものともせずに (wo monotomo sezu ni)", "wo monotomo sezu ni", "xavf-xatarga umuman pisand qilmay", "Ot + をものともせずに", "大雨[おおあめ]をものともせずに、作業[さぎょう]を続[つづ]けた。", "Ooame wo monotomo sezu ni, sagyou wo tsuduketa.", "Katta yomg'irga pisand qilmay ishni davom ettirishdi.")
]

print(f"Loaded {len(n1_grammar_rules)} official JLPT N1 grammar items!")
